app/templates/editor-documents/show.hbs
app/templates/inbox/archive.hbs

added read only functionaly to the archived folder

---

app/components/participation-list.hbs
translations/en-us.yaml
translations/nl-BE.yaml

added some error messages to the participation list to get the discussion started

add error messages to participation list

---

app/services/edit-stemming.js
app/services/store.js

Solves https://binnenland.atlassian.net/browse/GN-2060

when using the queryNestedRelationship function we didn't allow to set the page size and it defaulted to 20

---

app/components/behandeling-van-agendapunt.js

Solves https://binnenland.atlassian.net/browse/GN-2077?atlOrigin=eyJpIjoiMmJlMjE2ZDkwMTk5NGY3Y2JjZjczYzNkY2U3YjlmYTciLCJwIjoiaiJ9

when creating the editor document initialize the dates

---

app/components/behandeling-van-agendapunt.hbs
app/components/behandeling-van-agendapunt.js
app/components/meeting-form.hbs
app/components/meeting-form.js
app/components/participation-list.hbs
app/components/participation-list.js
app/components/participation-list/mandataris-row.js
app/components/participation-list/mandatarissen-table.hbs
app/components/participation-list/mandatarissen-table.js
app/components/participation-list/modal.hbs
app/components/participation-list/modal.js
app/models/behandeling-van-agendapunt.js
app/models/mandataris.js
app/models/zitting.js
package.json

fixes https://binnenland.atlassian.net/browse/GN-1810
linked:
https://github.com/lblod/app-gelinkt-notuleren/pull/19
https://github.com/lblod/notulen-prepublish-service/pull/18

Persist absentees as wel as participants

---

app/components/acmidm-login-compact.hbs
app/components/acmidm-login-compact.js
app/styles/_shame.scss
app/templates/components/acmidm-login-compact.hbs
package.json

rework acmidm login to be a glimmer component, replaced webuniversum components with appuniversum and bumped acmidm addon so it uses fetch instead of jquery

refactor acmdidm component to glimmer and bump acmdidm addon

---

app/templates/inbox/agendapoints.hbs

adresses 
https://binnenland.atlassian.net/browse/GN-2328
and possibly also
https://binnenland.atlassian.net/browse/GN-2305
and also
https://binnenland.atlassian.net/browse/GN-2334

Make the search box debounce

---

app/components/app-chrome.hbs
app/controllers/agendapoints/show.js
app/templates/agendapoints/show.hbs
translations/en-us.yaml
translations/nl-BE.yaml

Design update to the cloning of agendapoints:
- added a copy icon to the action
- changed the order of the actions in the dropdown
- added a dutch label

Clone agendapoints: add icon, change order of actions

---

app/adapters/application.js
app/components/agenda-manager/agenda-table/header.hbs
app/components/agenda-manager/agenda-table/row.hbs
app/components/participation-list.hbs
app/components/signatures/notulen/behandelingen-list.hbs
app/components/signatures/notulen/timeline-step.hbs
app/components/treatment/voting/modal.hbs
app/controllers/meetings/publish/notulen.js
app/models/gebruiker.js
app/routes/inbox/index.js
app/services/current-session.js
app/services/store.js
app/styles/_shame.scss
app/templates/mock-login.hbs
app/templates/print/uittreksel-error.hbs
config/environment.js

~~Based on #77 since that one also fixed some errors. I can rebase if needed.~~ I dropped the commit from this PR so this can be merged first if needed.

Fix the remaining linting errors

---

app/components/app-chrome.hbs
app/components/behandeling-van-agendapunt.js
app/components/meeting-form.hbs
app/components/participation-list/functionaris-selector.js
app/components/signatures/publication-confirmation.hbs
app/components/signatures/signature-confirmation.hbs
app/components/signatures/timeline-step.js
app/components/zitting/manage-zittingsdata.js
app/controllers/agendapoints/new.js
app/services/current-session.js
app/templates/inbox.hbs
app/templates/meetings/publish.hbs

This converts the CurrentSession service to a native class and removes all async properties since all they are guaranteed to be set once the application boots.

Modernize the CurrentSession service

---

app/components/behandeling-van-agendapunt.hbs
app/components/besluit-document-container.hbs
app/components/meeting-form.hbs
app/components/treatment/voting/voter-table.hbs
app/templates/agendapoints/edit.hbs
app/templates/agendapoints/new.hbs
app/templates/agendapoints/show.hbs
app/templates/inbox/loading.hbs
app/templates/meetings/publish/agenda.hbs
app/templates/meetings/publish/besluitenlijst.hbs
app/templates/meetings/publish/notulen.hbs
app/templates/meetings/publish/uittreksels.hbs
app/templates/mock-login.hbs
package.json

This version includes the updated datepicker and prevents AuModels `closeModal` from getting called twice.

Update ember appuniversum

---

app/components/agenda-manager/agenda-item-form/select-draft.js

Handle the case where the user clears the selected "draft"

---

app/components/agenda-manager/agenda-table/body.hbs
app/components/agenda-manager/agenda-table/index.hbs
app/components/agenda-manager/agenda-table/row.hbs
app/components/agenda-manager/index.hbs
app/components/behandeling-van-agendapunt.hbs
app/components/meeting-form.hbs
app/components/meeting-form.js
app/services/current-session.js

Read only role

---

app/models/zitting.js
app/routes/meetings/new.js

added a default value for free text in the model for sake of old meetings being backwards compatible

---

package.json

This resolves some dependency-lint conflicts.

Some dependency updates

---

app/components/signatures/signed-resource.hbs
app/styles/_shame.scss

depends on https://github.com/lblod/notulen-prepublish-service/pull/26

include calculated hash code when showing signature

---

app/controllers/meetings/publish/agenda.js
app/templates/meetings/publish/agenda.hbs

frontend changes required for https://github.com/lblod/notulen-prepublish-service/pull/33

make sure to pass type when creating agenda

---

app/components/meeting-form.hbs

This line of tryout code was left over from a previous pr, this removes it

Remove leftover AuLink

---

app/components/readonly-text-box.hbs
app/styles/_deprecated.scss
app/styles/_shame.scss
app/styles/app.scss
app/styles/project/_c-editor-preview.scss
app/styles/project/_c-template.scss

- refactor published template styles
- fix publish view collapse bug (content would collapse when certain items are expanded)
- add default table styles

Update publish styles

---

package.json

fixes some issues:
- spacing between tables
- selection focus after executing table actions
- no more header row in tables
- empty links are no longer included on pasting

bump rdfa editor

---

app/components/participation-list/mandataris-selector.js

solves https://binnenland.atlassian.net/browse/GN-2747
Afaict only vlaams-brabant actually has data for this atm, so it is only tested for them.

Allow governor to be selected if deputation

---

package.json

https://github.com/lblod/ember-rdfa-editor/releases/tag/v0.45.0
(see the [pre-release](https://github.com/lblod/ember-rdfa-editor/releases/tag/v0.45.0-0) for the changelog, this was my first time using release-it)

Bump ember-rdfa-editor to v0.45.0

---

app/components/behandeling-van-agendapunt.hbs
app/components/behandeling-van-agendapunt.js
app/components/meeting-form.hbs
app/components/meeting-form.js
package.json

Waiting for https://github.com/appuniversum/ember-appuniversum/issues/120

updated app universum and changed from au button to au link

---

app/components/readonly-text-box.hbs
app/styles/project/_c-editor-preview.scss

Add say-content styles to read only textbox to display consistent text styling.

Fix bullet points

---

app/styles/deprecated/_p-annotations-content-nl.scss
app/styles/project/_c-template.scss

Override old stylesheets so duplicate content is removed.

Fix overlapping text when signing

---

app/components/vo-page.hbs

This replaces the QA hostname with the production version.

Update the hostname in the footer

---

package.json

https://github.com/lblod/ember-rdfa-editor/releases/tag/v0.47.0

Bump editor to v0.47.0

---

app/components/participation-list/mandatarissen-table.hbs
app/components/treatment/voting/voter-table.hbs
app/styles/_shame.scss

Some tables were still relying on webuniversum. Added css for these cases and removed the old webuniversum classes.

Add styling for tables still relying on webuniversum css

---

app/templates/meetings/publish/uittreksels/index.hbs

Solved https://binnenland.atlassian.net/browse/GN-2900

Fixed page numbers in extract publication table

---

app/components/app-chrome.hbs
app/templates/meetings/edit/treatment.hbs
config/environment.js

I think we only need to hide the button as that would make the user unable to upload any attachment

Hide attachments behind feature flag

---

app/components/signatures/publication-status.hbs
app/components/signatures/publication-status.js
app/routes/meetings/publish/uittreksels/index.js
app/templates/meetings/publish/uittreksels/index.hbs

Depends on https://github.com/lblod/app-gelinkt-notuleren/pull/45

Calculated status based on the actual publication status of the extract

---

app/controllers/meetings/publish/notulen.js

Solves https://binnenland.atlassian.net/browse/GN-2902

Fix notulen was not correctly reloaded under a very specific scenario

---

Dockerfile

include all proxy config files in the build so the config gets picked up correctly

bugfix: allow large file uploads

---

app/components/app-chrome.hbs
app/templates/meetings/edit/treatment.hbs

found this while reviewing au-file upload pr

added attachment counter to ap edit route, fixed bug with undefined length

---

app/components/treatment/voting/modal.js

while working on a bug in this class I noticed the tasks where defined as
variables, which wans't inline with how we usually write these.

use generator methods instead of fields in vote modal

---

app/components/agenda-manager/agenda-item-form/select-location.hbs
app/components/agenda-manager/agenda-item-form/select-location.js
app/components/agenda-manager/edit.hbs

I know in the planning we said to leave the search functionality for later, but I took a look at the powerselect component and it seemed kinda easy to do. Let me know if I'm missing something but it worked when I tested it

added agendapoint position to the select and the search

---

package.json

should hopefully fix the build

bump rdfa editor to move to support ember-appuniversum in rdfa-editor

---

app/components/date-time-picker.hbs
package.json

- Change width of datepicker input field
- Update ember-appuniversum

Fix calendar popup overflow

---

app/styles/project/_c-template.scss

Add spacing and border above agendapoint in publication view (besluitenlijst & notulen).

Fix spacing between titles/articles in publication view

---

app/styles/project/_u-print.scss
app/templates/meetings/publish/uittreksels/show.hbs

Make print preview text smaller

Update print preview

---

package-lock.json
package.json

https://github.com/lblod/ember-rdfa-editor-roadsign-regulation-plugin/releases/tag/v0.3.0
* differentiate between absolute and relative urls and add path accordingly (@lagartoverde)
* Added temporal measures to the modal (@lagartoverde)

bump roadsign regulation plugin

---

config/targets.js
package.json

also expands the support version range a bit, supporting the last 2 versions
instead of just the latest stable

align both the browserlist and build targets

---

app/controllers/meetings/publish/notulen.js
app/templates/meetings/publish/notulen.hbs

we were using the zittingWrapper, but this removes treatments from the view

show actual notulen content for published notulen

---

package-lock.json
package.json

Updating dependency of the date-plugin to support the new insert location.

Updated dependency rdfa-date-plugin

---

package-lock.json
package.json

see https://github.com/lblod/ember-rdfa-editor/releases/tag/v0.56.3

Bump editor to v0.56.6

---

package-lock.json
package.json

This upgraded ember-appuniversum version includes the fix for the unexpected closing of the
modal when creating new meetings, agendapoints, ...

Fixing unexpected closing of AuModal

---

package-lock.json
package.json

This to allow testers to test the new editor on dev in a full GN env

Bump editor to v0.61.0-0

---

app/components/environment-banner.hbs
app/components/version-information-overview.hbs
app/styles/_shame.scss
app/templates/application.hbs

- style environment banner
- fix height issue on main-container when banner is visible
- fix meeting-sidebar offset when banner is visible

Environment banner styling and fixes

---

package.json

I think having the release command as part of the project scripts makes way more sense

Add release task to package.json

---

app/styles/_shame.scss
package-lock.json
package.json

Solves https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-3656.

Update toc plugin which fixes issues with overflowing entries

---

config/environment.js

Sets up the dev endpoints for local development

Add RB endpoints to devenv

---

app/controllers/regulatory-statements/edit.js
app/templates/agendapoints/attachments.hbs
app/templates/agendapoints/edit.hbs
app/templates/agendapoints/revisions.hbs
app/templates/regulatory-statements/edit.hbs
translations/en-us.yaml
translations/nl-BE.yaml

Solves https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-3771.

Add export-to-html menu action to regulatory-statements document view

---

app/controllers/regulatory-statements/edit.js
app/templates/regulatory-statements/edit.hbs

Add a prompt when a user tries to leave a page with a document that has changes without saving

add a prompt when a user tries to leave a page with unsaved changes in a document (GN-3740)

---

app/routes/irg-archive.js

Partial solution to https://binnenland.atlassian.net/browse/GN-3989?atlOrigin=eyJpIjoiM2Y3NTNlZDhmODMzNDZiMzhmOTQwNDc4NGVlZTcxMDUiLCJwIjoiaiJ9.

Reroute irg-archive to login when not authenticated

---

app/components/extracts/print-view.hbs

Pass correct property
https://user-images.githubusercontent.com/769698/218987460-a5b68718-8191-4e0c-aae7-b29d7ca34855.mp4

GN-4088: Fix backlink of print

---

app/controllers/agendapoints/edit.js
app/controllers/regulatory-statements/edit.js
app/templates/agendapoints/edit.hbs
app/templates/regulatory-statements/edit.hbs
config/environment.js
package-lock.json
package.json

Draft PR until https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/136 is merged

configure plugins without env variables

---

app/controllers/agendapoints/edit.js

https://binnenland.atlassian.net/browse/GN-4240

GN-4240: fix Change agenda point title in zitting editor

---

app/controllers/agendapoints/edit.js
app/controllers/regulatory-statements/edit.js
app/templates/regulatory-statements/edit.hbs
package-lock.json
package.json

Needed for: https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/135

make static TOC look the same in dynamic content

---

app/styles/_shame.scss

Solves bug in master where the powerselect in modals was not appearing.
Don't like this solution of increasing the z-index more and more each time, but well it works and doesn't need a entire rewrite of the css so...

Fix problem with powerselect not appearing

---

app/controllers/regulatory-statements/edit.js

Implement configuration for TOC scrolling to put the element on top of the page
[jira ticket](https://binnenland.atlassian.net/browse/GN-4200)
[Plugins PR](https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/177)
Needs to npm link the plugins repo, I will update the PR when the change is released
1 - Npm the plugins repo
2 - Go to regulatory statements
3 - create a document with a TOC
4 - click on a link of the TOC
5 - The element clicked should be at the top of the page
none

GN-4200: Implement new TOC scrolling functionality

---

app/components/publishing-log-document-name.hbs

a small change to #512 to remove an unnecessary if-statement. See #512 for all other info.

GN-4384 cleanup code (duplicate if-statement)

---

app/controllers/meetings/publish/uittreksels/index.js
app/routes/meetings/publish/uittreksels/index.js

By trying to be more explicit about resolving relationship promises, we lost the `meta` information that our ember-data serializer injects into the models.
(this comes from extending the ember-data-serializer-mixin, yeah, I know.)
This PR adds that back and also correctly defines the query params on the controller
[GN-4372](https://binnenland.atlassian.net/browse/GN-4372)
best way is to proxy to the QA database, and login as "gemeente edegem", there are some meetings with >20 APs there
you can compare with current QA for a/b testing
not sure about this, cause toArray may be deprecated. But as this is a hotfix, I tried to minimize changes
the page loads extremely slowly, but this was already the case. I already have a fix as well, but I left it out of scope here so we can release this pr …

GN-4372: fix pagination of extracts publish view

---

package-lock.json
package.json

see linked pr in plugins for more details
-------
[fixed in plugin pr 252](https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/252)
[jira issue](https://binnenland.atlassian.net/browse/GN-4451)
install, run
trivial, just try to run the plugin

GN-4451: fix rendered templates not showing in roadsign modal

---

.changeset/strange-wolves-divide.md
.changeset/stupid-cobras-pretend.md
package-lock.json
package.json

- Update editor to 8.2.0
- Update editor-plugins to 15.2.2

Update editor packages

---

.changeset/calm-baboons-itch.md
app/controllers/meetings/publish/notulen.js
app/models/versioned-notulen.js

fetch content from file if not present on the versioned-notulen

---

.changeset/soft-pets-exist.md
package-lock.json
package.json

-------
fixes #632
https://github.com/lblod/ember-rdfa-editor/pull/1177

fix: bump editor to v9.5.1

---

.changeset/gorgeous-pianos-brush.md
package-lock.json
package.json

This PR includes an update of `@lblod/ember-rdfa-editor-lblod-plugins` to 17.1.1

Update `@lblod/ember-rdfa-editor-lblod-plugins` to 17.1.1

---

.changeset/dull-doors-bow.md
package-lock.json
package.json

See [plugins PR](https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/479) for details.
Plugins PR: https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/479
Jira ticket: [binnenland.atlassian.net/browse/GN-5019](https://binnenland.atlassian.net/browse/GN-5019)
N/A
See [plugins PR](https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/479) for details.
N/A

Include snippet button fix

---

.changeset/serious-countries-provide.md
app/models/versioned-behandeling.js
app/models/versioned-besluiten-lijst.js
app/models/versioned-notulen.js

Add polymorphic to all meeting relationships

---

.changeset/pre.json
.changeset/small-stingrays-tie.md
CHANGELOG.md
app/controllers/inbox/meetings/new.js
app/models/behandeling-van-agendapunt.js
app/services/template-fetcher.js
tsconfig.json

draft because it's a bit _too_ ducktapey
TODO: need to figure out which URI is the most stable for a certain template

Preload the correct templates upon IV creation

---

.changeset/wild-starfishes-check.md
app/api/installatievergadering.js
app/controllers/inbox/meetings/new-inauguration.js
app/controllers/inbox/meetings/new.js
app/router.js
app/routes/inbox/meetings/new-inauguration.js
app/routes/inbox/meetings/new.js
app/templates/inbox/meetings.hbs
app/templates/inbox/meetings/new-inauguration.hbs
app/templates/inbox/meetings/new.hbs
app/utils/classification-utils.js
tsconfig.json

Bit of a refactor with the routes, and setup a (currently hardcoded) system for choosing the meeting variants
[GN-4989](https://binnenland.atlassian.net/browse/GN-4989)
Just run
Try out some of the municipalities that have an explicit config, check that making a normal  meeting also still works
I'm not sure yet how to do districts, as they seem to be in the db as municipalities
The special agenda items are still dummies on dev RB as we don't have the templates yet
We may want to move the config into data, I'm not sure which way is best but this was the easiest
Note: the newly fused municipalities are not yet in the GN database

Add system for meeting variants

---

.changeset/spicy-walls-relate.md
app/config/constants.js
app/config/mandatee-table-config.js

Now that LMB dev and qa have realistic data we can move to the new legislative
period

Switch to new governmental period for lmb queries

---

.changeset/calm-bikes-move.md
package-lock.json
package.json

This PR updates `@lblod/ember-rdfa-editor-lblod-plugins` to the latest dev commit corresponding to https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/494 .
Check-out the instructions out that PR to test it.

GN-5153: only trigger event handlers of snippet actions once

---

.changeset/large-pumas-cough.md
translations/en-us.yaml
translations/nl-BE.yaml

Clarify wording in export page
[GN-5179](https://binnenland.atlassian.net/browse/GN-5179)

Clarify download vs copy actions

---

.changeset/hip-islands-roll.md
app/services/editor/agendapoint.js

This seems to be quite a heavy query, and since it's querying persons they
should be quite stable, so a cached endpoint is already a quick improvement.
[GN-5201](https://binnenland.atlassian.net/browse/GN-5201)

use cached endpoint for lmb plugin

---

.changeset/metal-onions-guess.md
package-lock.json
package.json

PR created to test https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/504
[GN-5217](https://binnenland.atlassian.net/browse/GN-5217)
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/504
None
- Start the frontend
- Login as a municipality/OCMW
- Open/create an agendapoint
- Ensure you can now insert any electee in the document

GN-5217: person variable adjustments

---

.changeset/shiny-cars-approve.md
package-lock.json
package.json

Update `@lblod/ember-rdfa-editor-lblod-plugins` to version [27.0.3](https://github.com/lblod/ember-rdfa-editor-lblod-plugins/releases/tag/v27.0.3)

update editor-plugins to version 27.0.3

---

.changeset/long-eagles-rescue.md
.changeset/popular-seas-cheat.md
app/templates/legaal/cookieverklaring.hbs
app/templates/legaal/toegankelijkheidsverklaring.hbs
translations/en-us.yaml

This PR includes the following fixes to the legal pages of this app:
- (cookie statement): ensure the links are rendered as `a` tags + update them
- (cookie statement): replace IE link by Microsoft Edge link
- (accessibility statement): fix telephone number link
[GN-4536](https://binnenland.atlassian.net/browse/GN-4536?atlOrigin=eyJpIjoiZGE0OTk4MWEwZTY1NGRjMDhjM2U1ZDBjYWY4NzM4OGUiLCJwIjoiaiJ9)
- Visit the cookie statement page: ensure the links are rendered as `a` tags and resolve correctly
- Visit the accessibility statement: the telephone number link should now be correct

GN-4536: fix issues with legal pages

---

.changeset/clean-numbers-punch.md
package-lock.json
package.json

Just an update to the latest plugins.
Jira ticket: [binnenland.atlassian.net/browse/GN-5525](https://binnenland.atlassian.net/browse/GN-5525)
Plugins PR: https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/559
N/A
Publish previews show any variables (or OSLO locations) highlighted in orange.
N/A

Style variables as orange in previews

---

.changeset/fuzzy-toes-give.md
package-lock.json
package.json

https://binnenland.atlassian.net/browse/GN-5572

HOTFIX(5.53.x): Correctly instantiate template uris when inserting using standard-template-plugin
