lblod/frontend-gelinkt-notuleren

app/controllers/meetings/publish/agenda.js
app/controllers/meetings/publish/besluitenlijst.js
app/controllers/meetings/publish/notulen.js
app/controllers/meetings/publish/uittreksels.js
app/templates/meetings/publish/agenda.hbs
app/templates/meetings/publish/besluitenlijst.hbs
app/templates/meetings/publish/notulen.hbs
app/templates/meetings/publish/uittreksels.hbs

When changing to the publication page with a slow connection it shows the last published document for a few seconds (depends on how much time it takes to load the new prepublish document), if we try to publish this document errors happen.
By changing the .lastSuccessful attribute by .isIdle we solve this problem as we place the loading screen as soon as the user enters the screen

Changing last successful by is idle should solve all the problems

---

app/styles/project/_c-editor-preview.scss

Add a more compact styling for mandatee lists on the "uittreksels" and "notulen" publish view.

Quickfix for mandatee lists

---

app/app.js
app/config/custom-inflector-rules.js

I noticed this was placed inside the models folder, and needed a default export "hack" as well. I think moving it to a config folder makes sense?

Move the custom inflector rules file

---

.drone.yml
.eslintrc.js
app/routes/agendapoints.js
app/routes/application.js
app/routes/import.js
app/routes/inbox.js
app/routes/login.js
app/routes/meetings.js
app/routes/mock-login.js
app/routes/print.js
app/services/session.js
package.json

This replaces the ember-simple-auth mixins with session service based alternatives.

Remove the ember-simple-auth mixins

---

.drone.yml

This PR:
- adds a separate install step to make the logs more readable
- adds back the "test" step but it is allowed to fail now
- moves the build step to the end so it only runs when the linting step succeeds possibly saving pipeline time.

Drone.io config tweaks

---

app/components/agenda-manager/agenda-item-form/select-draft.hbs
app/components/agenda-manager/agenda-item-form/select-location.hbs
app/components/language-select.hbs
app/components/participation-list/functionaris-selector.hbs
app/components/participation-list/mandataris-selector.hbs
app/components/zitting/manage-zittingsdata.hbs
package.json

This should also fix the deprecation warnings about `-in-element` when building the app. 
Ideally `@lblod/ember-rdfa-editor-besluit-type-plugin` should be updated as well because now there are still 2 versions of ember-power-select being installed. ember-cli-dependency-lint wouldn't like that :smile:.

Update to ember-power-select 4.1.4

---

.drone.yml
config/dependency-lint.js
package.json

This adds a pipeline step that runs ember-cli-dependency-lint but is ignored when failed.
Multiple versions of the same Ember addons should be avoided since that can lead to weird bugs and behavior.

Lint ember dependencies during CI

---

app/components/agenda-manager/agenda-item-form/select-draft.hbs
app/components/agenda-manager/agenda-item-form/select-location.hbs

This argument did not actually do anything without setting a tagName and that isn't possible anymore since it uses Glimmer components now. The classes aren't neither either since appuniversum uses the power-select classes directly.

Remove the @class argument from <PowerSelect>

---

app/components/date-time-picker.hbs
app/components/date-time-picker.js
app/styles/app.scss
app/styles/project/_c-meeting-chrome.scss
package.json
translations/appuniversum/en-us.yaml
translations/appuniversum/nl-be.yaml

This includes the ember-appuniversum update commit from #95 as well to make it easier to test.

Replace <WuDatepicker> with <AuDatePicker>

---

app/components/zitting-link.js

Fixes GN-2639 with a workaround, as discussed.

Don't link to the "meeting" page after removing the agenda item

---

app/models/artikel.js

`@lblod/ember-rdfa-editor-citaten-plugin` doesn't export this model class anymore.

Remove "Artikel" model

---

app/components/agenda-manager/agenda-context.hbs
app/components/agenda-manager/agenda-context.js
app/components/agenda-manager/edit.js
app/components/agenda-manager/index.hbs
app/components/agenda-manager/index.js
app/models/behandeling-van-agendapunt.js

This rolls back the changes to the `Agendapunt` and `BehandelingVanAgendapunt` records when closing the modal without saving. This also means the newly created records are deleted.
This should fix both GN-2604 and GN-2605.

Agendapoint record cleanup

---

app/routes/application.js
app/templates/application.hbs

This sets the application title using the `{{page-title}}` helper. This allows other pages to also use the helper without overriding the base title.

Set the application title using `{{page-title}}`

---

app/components/administrative-body-select.hbs
app/components/administrative-body-select.js
app/components/meeting-form.hbs
app/components/required-field.hbs
app/components/zitting/manage-zittingsdata.hbs
app/components/zitting/manage-zittingsdata.js
app/controllers/inbox/meetings.js
app/controllers/inbox/meetings/new.js
app/controllers/meetings/new.js
app/router.js
app/routes/inbox/meetings/new.js
app/templates/inbox/meetings.hbs
app/templates/inbox/meetings/new.hbs
app/templates/meetings/new.hbs
package.json
translations/en-us.yaml
translations/nl-BE.yaml

This changes the meeting creation flow. Instead of showing a "faux" edit page on which the user needs to click a button to open a modal, it now opens a modal directly. It also validates that an administrative body is selected before a meeting is created. On the edit page the administrative body is now readonly (GN-2651).

Meeting creation flow changes

---

app/components/editor-document-title.hbs
app/components/editor-document-title.js

I noticed that typing in a title showed an exception in the console.
Did a little refactoring while I was at it :smile:.

Fix `<EditorDocumentTitle>` exception

---

app/components/zitting/manage-zittingsdata.hbs

This makes sure changes to the meeting data are reverted when closing the modal by pressing escape or clicking outside of it.

Alway revert "meeting"  data changes when closing

---

app/styles/project/_c-template.scss

inspired by https://github.com/lblod/frontend-gelinkt-notuleren-publicatie/pull/30
-     remove double comma's
-     fix incorrect margins
-     remove double icons
-     make print view typography smaller
left hand side shows improvements

fix layout of publication preview (based on the work dieter did on the publication frontend)

---

app/styles/project/_u-print.scss

Fixes the issue when the div with the mark-highlight-manual class is not printed.

show mark-highlight-manual on print view

---

package.json

This removes yet another dependency on the old ember webuniversum styles :partying_face:

bump import snippet plugin

---

translations/en-us.yaml
translations/nl-BE.yaml

Not all publications lead to notification (melding). The wording we had did not reflect that.

Improve wording around notification

---

app/services/publish.js

The prepublisher emits jobs for lengthy operations.  With this we consume these in a polling loop.
Next:

Consume job for prepublishing

---

translations/en-us.yaml

Made consistent with the other labels

Fix typo in outro component

---

app/styles/_deprecated.scss

Scrolling behaviour in the editor was broken with the removal of webuniversum.
Added back the container-flex--contain class to revert to the correct scrolling behaviour.

fix editor scrolling issue

---

package.json

As far as I can tell, this was caused by the besluittype plugin generating errors which caused some rendering hiccups. The latest version of that plugin solves the issue. 
The problem only appeared on prod, cause the kind of errors it generated are only warnings when running local dev server, but errors on prod. 
This pr is then just a version bump, but also a bugfix
Fixes https://binnenland.atlassian.net/browse/GN-2944

Fix issue with double characters

---

app/components/document-attachments.hbs

Related to this issue https://binnenland.atlassian.net/browse/GN-2967

Change column order in attachments table

---

app/components/document-attachments.hbs
app/components/document-attachments.js
config/environment.js

there will not be more types any time soon, so I feel this will be a bit more clear to users.

convert the type selector to a toggle

---

app/components/document-attachments.hbs
translations/en-us.yaml
translations/nl-BE.yaml

An attempt to make it a bit more clear how it works. 
@Dietr not sure about the placement of the warning (currently inside the table and feels a bit messy). 
In general: might consider just converting this to a regular info box and always show it?

add a warning to attachment overview if no decisions were found

---

app/components/agenda-manager/agenda-context.js

the value of geplandOpenbaar on the agendapoint should be the default for "openbaar" on the treatment, this was not the case.

correctly set the default for "openbaar" on treatment

---

Dockerfile
ember-cli-build.js

The option `collapse_vars` was disabled on Terser and this caused the RAM usage to spike for some reason, failing the build due to out of memory problems. Removing this option leaves Terser with its own defaults and that seems to produce correct builds.

Fixing production builds "out of memory" problems

---

app/components/agenda-manager/agenda-item-form/select-location.js
app/components/agenda-manager/edit.hbs

We can now add agendapoints to the beginning or end of the list when there is at least 1 agendapoint (previously 2), and the agendapoints now show correctly at the end of the list when chosen so. These were "off by one" errors on collections.

Fixed off by one errors on adding agendapoints

---

app/components/document-creator.js

Use trim to remove the whitespace around the text and see if the length is still greater than 0. Also trim the title when saving, because extra spaces are sometimes shown (when editing the title while editing the agendapoint) and sometimes not (in the inbox and while not editing the title) due to the way HTML collapses whitespace, but not in inputs.

Trim title on validation and on saving Agendapoint

---

app/components/attachments-number.js

Fixes https://binnenland.atlassian.net/browse/GN-3396, basically the meta count is not updated but the length of the attachments is.
Maybe also something we should check with Aad

fix attachments number in the agendapoints screen

---

app/styles/project/_c-template.scss

Fixes https://binnenland.atlassian.net/browse/GN-3417.
I didn't find any use for that block of css but you will know better than me

Removed style that displayed article number as block

---

app/components/zitting/manage-zittingsdata.hbs
app/components/zitting/manage-zittingsdata.js
translations/en-us.yaml
translations/nl-BE.yaml

added validation to meeting end date/time

---

app/styles/project/_u-print.scss

Buttons with display none made tables do weird things in print view and crashes the print preview.
Fix: hide buttons with opacity seems to fix this. No clear idea why this is happening though.

Fix chrome print bug

---

package-lock.json
package.json

This update fixes an issue with willDestroy-hooks not being triggered as the previous version of this package caused an exception.

update package version of citaten-plugin

---

app/components/agenda-manager/edit.hbs
app/components/agenda-manager/edit.js

Solves https://binnenland.atlassian.net/browse/GN-3425

changing the geplandOpenbaar of an agendapoint affects the openbaar of a behandeling

---

app/components/zitting-text-document-container.js

Fixes the issue when it's not clear where the text cursor/area is. Adding the paper view makes this more clear in full screen situations.

Use paper view for intro and outro editor

---

app/components/agenda-manager/edit.hbs
app/components/agenda-manager/edit.js

This PR disables the cancel and delete buttons when saving an agendapoint, as well as disabling closing the modal altogether.
https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-3527

Disable closing the edit agendapoint modal when saving

---

README.md
app/components/environment-banner.hbs
app/components/environment-banner.js
app/components/version-information-overview.hbs
app/components/version-information-overview.js
app/styles/app.scss
app/styles/project/_c-environment-banner.scss
app/templates/application.hbs
config/environment.js

This PR adds an environment banner which includes the environment name and application version. Additionally it provides a button which leads to an overview of the editor version and the versions of the editor-plugins installed.
It is still to be seen if the way how the environment is populated with the package versions is a desirable one.

Addition of an environment banner

---

package-lock.json
package.json

Roadsign-regulation plugin added as a github dep until [this PR](https://github.com/lblod/ember-rdfa-editor-roadsign-regulation-plugin/pull/47) is merged. This way this pr still fully builds correctly without having to wait on a release.
(But it would still be better to wait before merging.)
More context: this bump is actually quite important, since it fixes compat with the 0.63.3 release. It would be easy to end up with that release accidentally since it's within semver range of the package.json
EDIT: plugin version released and package.json updated

chore(deps): bump editor and plugins to newest bugfix releases

---

app/services/regulatory-attachments-fetcher.js

First of all this depends on https://github.com/lblod/reglement-publish-service/pull/5 so we should wait for that to be merged and deployed, but I created the PR so we can start a little discussion.
I did the most basic thing, if the reglement has an expiration date not show it, I was thinking on filtering based on the ones that are still valid (even thought we don't really set this validthrough date in the future, we just set it to today when we delete in the regulatory statements app). This would be more semantically correct, but also would bring the question: "Do we want to allow the user to include a template that will expire tomorrow, in the next week...?", I think that for the moment is better to leave it like this and improve the flow in the future, but it's open for discussion

Filter based on validThrough property

---

app/controllers/inbox/agendapoints.js
app/controllers/inbox/regulatory-statements.js
app/routes/inbox/agendapoints.js
app/routes/inbox/regulatory-statements.js
app/templates/inbox/agendapoints.hbs
app/templates/inbox/regulatory-statements.hbs

- fix(RS): fix default sorting, search and pagination for RS overview
- fix(agendapoints): make the pagesize param actually do something
solves https://binnenland.atlassian.net/browse/GN-3735

Fix sorting, search and pagination on RS overview page

---

app/components/document-creator.js

The previous regex did not escape some characters which caused the match to fail. Partly a solution for https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-3682.

Fix regex which matches for generateUuid() in the template

---

app/components/confirm-route-leave.js
app/utils/is-loading-route.js

This PR checks if a transition target is a loading route when trying to show a confirm dialog. When it is a loading route, the dialog isn't shown.

Fix: prevent the confirm dialog to show up twice when exiting without saving

---

app/styles/project/_u-print.scss

Reset table styles on print: seems to be the cause of the infinite pages issue on print.
Needs thorough testing as the issue is not always present. In my tests it always showed when there are votes made with an agendapoint.

Fix infinite pages when printing a meeting

---

app/controllers/regulatory-statements/edit.js

This PR fixes the method call syntax in order to save a regulatory statement which prevents an error.

Fix syntax issue that caused error when saving regulatory statement

---

app/components/treatment/voting/modal.js
app/models/behandeling-van-agendapunt.js
app/models/stemming.js

This PR includes two fixes:
* For a specific treatment of an agendapoint, all votings are fetched and not only the first 20.
* The positions of the votings are fixed automatically when a voting is removed in the middle of the list.
This PR is to be used in combination with: https://github.com/lblod/app-gelinkt-notuleren/pull/118 and solves https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-3798

Fix issue with voting overview page where the number of votings are limited to 20

---

app/components/meeting-form.hbs
app/components/meeting-form.js
translations/en-us.yaml
translations/nl-BE.yaml

Solves https://binnenland.atlassian.net/browse/GN-3640, I saw the issue and was simple so I implemented it, this has to be revisited if we implement the ability to republish a meeting, but for the moment it prevents confusion by the user.
@Dietr I used a simple design to show the user that a notulen has been published, just a pill on every heading, maybe you want to modify that

When the notulen is published disable the editing

---

app/components/editor-document-title.js

Solves https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-3826.

Bugfix: only return title property if this._title is null or undefined

---

app/components/editor-plugins/regulatory-statements/search-modal.hbs
app/components/editor-plugins/regulatory-statements/search-modal.js
app/components/editor-plugins/regulatory-statements/sidebar-insert.hbs
app/services/document-service.js
package-lock.json
package.json
translations/en-us.yaml
translations/nl-BE.yaml

This PR does two things:
- It adds an `already attached` indication to regulatory statements which are already included.
- It disables the `insert` button when a statement is already coupled.
This PR solves https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-3810

Feature: prevent the duplicate inclusion of regulatory statements in a decision

---

app/components/editor-plugins/regulatory-statements/sidebar-insert.js

Ensure the besluit modelNode is always up to date.

Move besluit property in regulatory statement plugin to dynamic getter.

---

app/controllers/regulatory-statements/edit.js

This PR ensures that the _editorDocument property is tracked in the regulatory statements edit page.
Fixes https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-3826.

Fix weird title behaviour in regulatory statements edit page.

---

app/components/app-chrome.hbs
app/components/app-chrome.js
app/components/editor-plugins/regulatory-statements/view.hbs
app/components/editor-plugins/regulatory-statements/view.js
app/components/regulatory-statement-link.hbs
app/components/regulatory-statement-link.js
app/routes/inbox/agendapoints.js
app/routes/inbox/regulatory-statements.js
app/templates/inbox/regulatory-statements.hbs
app/templates/regulatory-statements/show.hbs

This PR ensures that published regulatory statements are not editable. It also ensures that logged in, read-only users dont see the editable view.
This PR solves https://binnenland.atlassian.net/browse/GN-3835?atlOrigin=eyJpIjoiYjAzMWJiOGM5ZTBhNGM5OGJkNmI1YWRlNDdlMWYwYWUiLCJwIjoiaiJ9.

Feature: non editable published regulatory statements

---

app/components/confirm-route-leave.js

When cancelling the "are you sure you want to leave without saving" prompt when you click the browser back button, it should reset back to the url you were on.
https://user-images.githubusercontent.com/115715476/203875573-ce534561-dcf9-48b8-beb6-a5a548e2c62c.mp4
This fix is because of this issue: https://github.com/emberjs/ember.js/issues/18620 .
I also included a video, in which I tested every case I could think of.

reset back to the url you were on after cancelling redirect

---

app/components/agenda-punt-link.hbs
app/components/editor-document-title.hbs
app/components/regulatory-statement-link.hbs
app/helpers/limit-content.js
translations/en-us.yaml
translations/nl-BE.yaml

Solves https://binnenland.atlassian.net/browse/GN-2674

Make title error visible and wrap when content is long

---

app/controllers/agendapoints/edit.js

In order to prevent users from being able to create “faulty” documents by copy pasting etc, we would remove decisions that don’t have any content from the document when saving.

hotfix: remove empty decisions from document on save

---

app/styles/_shame.scss

This PR adds some CSS (similar to the CSS on the publication environment) in order to hide empty voter divs included in the notulen preview.

Hide empty voter divs in notulen preview

---

app/components/agenda-manager/agenda-item-form/select-draft.js
app/components/editor-plugins/regulatory-statements/search-modal.js
app/templates/inbox/agendapoints.hbs
app/templates/inbox/irg-archive.hbs
app/templates/inbox/meetings.hbs
app/templates/inbox/regulatory-statements.hbs
app/templates/inbox/trash.hbs
app/templates/meetings/publish/uittreksels/index.hbs

This PR ensures that most text-attributes (such as titles) are sorted in a case-insensitive way.
To be tested in combination with https://github.com/lblod/app-gelinkt-notuleren/pull/140.
Solves https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-3912

Add case insensitive sorting to all text-based/title columns

---

app/components/application-header.hbs
app/components/application-header.js
app/components/vo-page.hbs
app/router.js
app/templates/inbox.hbs
app/templates/not-found.hbs
translations/en-us.yaml
translations/nl-BE.yaml

This PR does two things:
- Addition of an application-header component which either shows a login button, or the status of the currently logged in user, if there is one.
- Addition of a not-found route which matches either non-defined route path. It shows a message to a user and a link to the contact-page.
Partial solution to https://binnenland.atlassian.net/browse/GN-3989?atlOrigin=eyJpIjoiMmI3MmY1NmQxYWRkNDY4ODlkZTVmOGJkNGIyMGRjOWUiLCJwIjoiaiJ9.

Addition of not-found route

---

app/adapters/application.js
app/components/not-found-warning.hbs
app/components/not-found-warning.js
app/components/vo-page.hbs
app/components/vo-page.js
app/routes/agendapoints.js
app/routes/regulatory-statements/edit.js
app/templates/agendapoints-error.hbs
app/templates/irg-archive/error.hbs
app/templates/meetings/error.hbs
app/templates/not-found.hbs
app/templates/regulatory-statements/error.hbs
translations/en-us.yaml
translations/nl-BE.yaml

This PR ensures that an error message is shown to the user when a document could not be fetched.
Partial solution to https://binnenland.atlassian.net/browse/GN-3989?atlOrigin=eyJpIjoiNGQ0OTg0ZWNhYjkxNDVhMGE5MmYwN2RjZGVlZjQ1ZTciLCJwIjoiaiJ9.

Add error routes to agendapoints, regulatory statements, meetings and the irg-archive

---

app/components/editor-plugins/regulatory-statements/search-modal.hbs
app/components/editor-plugins/regulatory-statements/sidebar-insert.js
app/components/editor-plugins/regulatory-statements/view.hbs
app/components/editor-plugins/regulatory-statements/view.js
app/templates/agendapoints/edit.hbs
translations/en-us.yaml
translations/nl-BE.yaml

This PR includes the following fixes/updates:
- Update of `AuAlert` components in regulatory-statement search-modal
- Fix issue with document content overflowing in regulatory-statement search-modal
- Fix issue with edit button not showing on regulatory-statement view
- Update regulatory-statement plugin to use the new editor API

Update internal regulatory statement to support new editor API

---

app/components/editor-document-title.hbs
app/components/editor-document-title.js
app/templates/application.hbs
translations/en-us.yaml
translations/nl-BE.yaml

Solves https://binnenland.atlassian.net/browse/GN-4208, I couldn't reproduce the issue on local while I can easily do it on dev and qa, so it must have been fixed by other PR in the meantime.
I solved the issue where you could save a title even if it was unchanged

avoid saving editor document title without changes

---

app/components/zitting-text-document-container.hbs
app/components/zitting-text-document-container.js

This PR solves an issue with the intro and outro editors of a meeting no being loaded correctly. This is due to the date plugin not being configured correctly. This PR ensures that the date plugin is correctly added and configured for both the outro and intro editors.
Solves https://binnenland.atlassian.net/browse/GN-4331?atlOrigin=eyJpIjoiMzk5NDFhOTgyNjI4NDFmY2JmMjEzYmY1ZGUwNTUxMzUiLCJwIjoiaiJ9

Add date plugin to zitting-text-document-container and fix date config error

---

app/components/signatures/signed-resource.hbs

Changed the date on the signed resource to be placed on the left of the signer instead of the bottom
[jira ticket](https://binnenland.atlassian.net/browse/GN-4361)
Depends on #493 just because it was easier to style without the hash block
No setup needed
Go to a meeting, go to publish, sign whichever document you want see that the date is now placed on the left of the signer
https://github.com/lblod/frontend-gelinkt-notuleren/assets/17006446/3bd3f603-9c66-4680-b58f-6dd12c5ec7ad
I'm happy with the responsive behaviour but maybe we want to put the date below in certain cases seen in the video, open for discussion

Place the date on the right of the signer

---

app/components/signatures/signed-resource.hbs

Removed the hash from the signed resource that appears on the publish screen for all the documents (agenda, decision list, notulen...) as this is no longer needed because it appears on the publication actions screen
[jira ticket](https://binnenland.atlassian.net/browse/GN-4356)
No setup needed
Go to a meeting, go to publish, sign whichever document you want, see that the hash no longer appears
None

Hide hash on signed resource

---

translations/en-us.yaml
translations/nl-BE.yaml

This removes the text "signing is irreversible" from the modals, as signing can now be reversed by deleting a signature.
https://binnenland.atlassian.net/browse/GN-4354
Sign anything, see the confirmation dialog box. Jira ticket has a video showing it.
I checked any other instances where this might be mentioned, but found nothing.

GN-4354: Remove text "irriversible" from sign modal

---

app/templates/meetings/publish/publication-actions/index.hbs

This PR ensures that the design of the publication actions page is consistent with the original figma design and the other publication pages (such as uittreksels). I adds a title to the page and removes the padding around the table.
None
Visit the publication-actions overview page

Make design of publication-actions page consistent with designs of other publication pages

---

app/controllers/meetings/publish/notulen.js

For notulen, the VersionedNotulen you sign is not the same as the one
you publish. So I had to revert my earlier change to go back to saving
any non-empty signedresource relationships.
<https://binnenland.atlassian.net/browse/GN-4362> 
See ticket, make meeting, sign, then publish before, signature
dissapeared now, it doesnt 
-   [X] UI: works on smaller screen sizes
-   [X] UI: feedback for any loading/error states
-   [X] Check cancel/go-back flows
-   [X] Check database state correct when deleting/updating (especially
regarding relationships)
-   [X] changelog
-   [X] npm lint
-   [X] no new deprecations

GN-4362 fix signatures disappearing after publishing

---

app/controllers/agendapoints/edit.js
app/controllers/regulatory-statements/edit.js
config/environment.js
package-lock.json
package.json

- feat(config): set dev roadsigns to uncached endpoint
- fix(variables): use correct number variable config
also bumps plugins to v8.2.2
https://binnenland.atlassian.net/browse/GN-4403

GN-4403: use correct config for variables

---

app/components/publishing-log-document-name.js
app/controllers/meetings/publish/publication-actions/index.js
app/routes/meetings/publish/publication-actions/index.js
app/templates/meetings/publish/publication-actions/index.hbs
translations/en-us.yaml
translations/nl-BE.yaml

This PR adds a dropdown component to the publication actions page which allows users to filter on document type.
The values a user can select between are:
- Agenda
- Decision list
- Extract
- Document/Notulen
Jira ticket: https://binnenland.atlassian.net/browse/GN-4358?atlOrigin=eyJpIjoiOTViNmRjMzcwN2ExNGJkY2E5YTMyZTNkZDc2MzY1ODMiLCJwIjoiaiJ9
Design: https://www.figma.com/file/pW370BHe4ES5eN0vHhArA5/GN-4022?type=design&node-id=0-1&t=Ncms3NPhRgxXECZW-0
Visit the publication actions page and select a document type using the dropdown. Only the selected document type should be shown and the pagination should reset to page 0.

GN-4358: addition of a document-type filter to the publication actions page

---

app/controllers/regulatory-statements/edit.js

This PR adapts the schema of regulatory statement documents in order to ensure root-level articles are allowed.
https://binnenland.atlassian.net/browse/GN-4407?atlOrigin=eyJpIjoiYTMyOTdkMzg4MjY0NDUwNWJmMjlkMWM4NzViOThlZjYiLCJwIjoiaiJ9
https://binnenland.atlassian.net/browse/GN-4406?atlOrigin=eyJpIjoiY2E4MGNiZjk3NDIxNDgxNjg5NjYwMzg4NTU0MTZhOWIiLCJwIjoiaiJ9
- Create a new regulatory statement document based on a template containing root-level articles.
- Check if the articles are correctly parsed
- Check if you can add root-level articles

GN-4406: add support for root level articles to regulatory statement documents

---

app/controllers/meetings/publish/agenda.js
app/controllers/meetings/publish/besluitenlijst.js
app/controllers/meetings/publish/notulen.js
app/routes/meetings/publish/uittreksels/index.js
app/services/publish.js

There were still a few locations where we were filtering only on deleted = false, but this also filtered out all existing signatures/publishedResources, 
because in sparql, deleted=false implies that the triple exists in the first place.
https://binnenland.atlassian.net/browse/GN-4427
bit difficult as you need signatures that doesn't have the deleted triple. The best way is to 
get a prod backup and test with known published (as per publicatie) documents.

GN-4427: fix old signatures and publications not being picked up

---

app/components/behandeling-van-agendapunt.hbs
app/components/behandeling-van-agendapunt.js
app/components/participation-list.hbs
translations/en-us.yaml
translations/nl-BE.yaml

Originally, it was always possible to edit the participants in an agendapoint. However, the votings attached are closely related: only present participants can vote. When creating a vote and then changing the participants, this would create a mismatch between both.
In most cases this gave no bugs, except for the voting making less sense.
In the case of removing *all* participants after adding votes, the votes would be hidden, but still exist. This means that when publishing, the voting would suddenly pop up again. This is the bug mentioned in the ticket.
This fixes this by not allowing participants changes for an agendapoint that has votings.
https://binnenland.atlassian.net/browse/GN-4430
Getting the bug of a vote showing up when there are no votes in the edit page:
For an agenda: 
1. …

GN-4430: Don't allow editing agendapoint participants if votings are present

---

.changeset/proud-bats-yell.md
app/controllers/agendapoints/edit.js
app/controllers/regulatory-statements/edit.js
app/services/current-session.js
app/utils/bestuurseenheid-classificatie-codes.js

This PR ensures that the municipality field of the `edit-address` card is only prefilled when the current user is part of a municipality or OCMW. The code in this PR checks if the currently logged in user has one of the two following classification codes:
- http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001 (Gemeente)
- http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000002 (OCMW)
[GN-4509](https://binnenland.atlassian.net/browse/GN-4509?atlOrigin=eyJpIjoiYTRmNjJlZjg4ZTJjNDM5MmI4YTZkNGVjYWU2ZGE5OTEiLCJwIjoiaiJ9)
- Log in as a municipality/OCMW (e.g. Aalst)
- Notice that when trying to edit a newly inserted address, the municipality field is prefilled with the municipality name
- Log in as as an …

GN-4509: only prefill address municipality if logged in user is part of a municipality/OCMW

---

.changeset/pretty-walls-wonder.md
.woodpecker/.test-pr.yml
package-lock.json
package.json

GN-4528: Fix issues reported by `dependency-lint`
* fix issues reported by `dependency-lint`
* require `dependency-lint` CI job to pass
Most of the issues reported were fixed by reducing the major version that was bumped by dependabot. 
The trickiest one was forcing `@appuniversum/ember-appuniversum` to resolve `tracked-toolbox` to `^2.0.0`. Turns out you need to use `overrides` field for `npm` not `resolutions` like `yarn` does 😵‍💫 
Using overrides is the expected approach from appuniversum team - https://github.com/appuniversum/ember-appuniversum/pull/421#issuecomment-1706553230
https://binnenland.atlassian.net/browse/GN-4528
1. Checkout
2. `npm i`
3. `ember dependency-lint`
`ember dependency-lint` should pass

GN-4528: Fix issues reported by `dependency-lint`

---

.changeset/strong-rabbits-travel.md
package-lock.json
package.json

Updates the `@lblod/ember-rdfa-editor` package to 6.2.0 which includes embedded-editor fixes and a `say-content` sass-mixin.

Update `@lblod/ember-rdfa-editor` to 6.2.0

---

.changeset/pink-readers-destroy.md
app/styles/app.scss

Some preview content in GN did not show the same as content on other places. The problem comes from a missing class `say-content`.
This adds the same styling of `say-content` to `c-template-content--treatment`, which contains this content where the styling was missing.
https://binnenland.atlassian.net/browse/GN-4210
https://github.com/lblod/ember-rdfa-editor/pull/989
npm link the editor
`npm link @lblod/ember-rdfa-editor` in this repo
See ticket for a specific example. The easiest is to add some superscript/subscript to an agenda item and see that this is rendered correctly on any place an agenda item is rendered.
I wanted to avoid this solution as it is a bit hacky (and needs an editor change)
However:
- changing the preview means changing the notulen-prepublish-service template, which …

Add say-content styling to all treatment content (Fixes sub/superscript)

---

.changeset/wet-forks-smell.md
app/components/editor-document-title.hbs
app/components/editor-document-title.js
app/utils/strings.js

See mostly https://github.com/lblod/frontend-reglementaire-bijlage/pull/191 (copied from there)
- Empty titles are not permitted
- If title is empty, an error shows up
- save pill is only shown if something is actually saved
- save pill logic is a lot simpler and more logical, using the state of ember-concurrency, instead of keeping the exact same state ourselves.
- title is automatically save if focus is lost. => **ticket fix**: this fixes the original ticket issue. When pressing save-document button, the title input box will lose focus, making it automatically save together with saving the document.
[binnenland.atlassian.net/browse/GN-4473](https://binnenland.atlassian.net/browse/GN-4473)
similar changes in https://github.com/lblod/frontend-reglementaire-bijlage/pull/191
- try to save …

Also save title when saving document + fix save pill and don't allow empty titles

---

.changeset/two-pants-thank.md
app/components/document-creator.js
app/controllers/agendapoints/edit.js
app/controllers/regulatory-statements/edit.js
app/models/template.js
app/routes/agendapoints/edit.js
app/routes/inbox/agendapoints/new.js
app/routes/regulatory-statements/edit.js
app/services/standard-template.js
app/templates/agendapoints/edit.hbs
app/templates/regulatory-statements/edit.hbs
package-lock.json
package.json

Pull standard-template-service from plugins and pass templates in to the standard template plugin.
Edit: modified to also pass in classificatieUri to besluit-type-plugin as needed by [plugins](https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/314)
https://binnenland.atlassian.net/browse/GN-4525
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/313
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/314
Needs the latest plugins as that uses the passed in templates correctly. This shouldn't break with older versions of the plugins though as it's simply passing in an arg that isn't used.
Test that editing agenda points and inserting templates works as expected.
N/A

GN-4525 Changes to support removal of ember-data from plugins

---

.changeset/famous-balloons-smell.md
app/components/rdfa-editor-container.hbs
app/components/rdfa-editor-container.js

This PR ensures that the editor component is only initialized after the prefix attribute of it's wrapping container has been set.
This PR:
- introduces a `setUpPrefixAttr` modifier on the wrapping container which sets the prefix attribute. It also controls the `ready` property which indicates when the editor may be initialized.
* After the `prefix` attribute has been set, the `ready` property is set to `true`
* When the element linked to the `setUpPrefixAttr` modifier is destroyed, the `ready` property is set to `false` (as the prefix attribute no longer exists)
=> this also means that the `setUpPrefixAttr` modifier is not generic and is only meant to be used in combination with the wrapping container.
This PR should solve the issue with the datastore calculation after having saved a …

GN-4529: ensure editor is only initialized after prefix attribute of wrapping div has been set

---

.changeset/wild-melons-dress.md
app/components/document-creator.js
app/services/regulatory-attachments-fetcher.js

```ts
/**
* Document Creator component is used by two different screens:
*   - Create agenda point flow
*   - Create regulatory statements flow
*
* `templates` coming from regulatory statements flow are _NOT_ `TemplateModel` instances,
* they are just plain objects with a `title` and a `loadTemplateBody` property. So we
* have to use `loadTemplateBody` to load the template body if we need to build the template
* when creating a regulatory statement.
*
* This was previously checking and calling `this.template.reload`, but that was causing
* `reload` to mutate from function to a "boolean" when `TemplateModel` of `ember-data` is used,
* causing errors when calling `reload` on the template again, as it became a boolean.
*
* The fix was to change `reload` to `loadTemplateBody` in …
```

 GN-XXX: Fix agendapoint/regulatory attachment template "reload"

---

.changeset/tricky-countries-bake.md
app/components/zitting-text-document-container.hbs
app/components/zitting-text-document-container.js

This PR fixes an issue where the editor instances of an intro/outro of a meeting were not correctly rendered.
Specifically, this PR updates the import paths of the `date-variable` plugin in the `zitting-text-document-container` component.
[GN-4607](https://binnenland.atlassian.net/browse/GN-4607?atlOrigin=eyJpIjoiZDBjNjRlZDFmNDVkNGEzMGI2YmFhMTYxYzVlNzM5YmQiLCJwIjoiaiJ9)
**Before this fix**
- Open the intro/outro of a meeting
- The editor-component is blank and an error shows up
**After this fix**
- Open the intro/outro of a meeting
- The editor-component is correctly rendered. It is possible to insert and edit a date.

GN-4607: fix issue with editor of meeting intro/outro not rendering

---

.changeset/weak-pumpkins-remain.md
app/components/rdfa-editor-container.hbs
translations/en-us.yaml
translations/nl-BE.yaml

In the sidebar, this used to say 'Insert':
https://binnenland.atlassian.net/browse/GN-4665
Recommended, some way to change locales easily, e.g. [this extension](https://addons.mozilla.org/en-US/firefox/addon/locale-switcher/)
Open any agendapoint or regulatory statement and confirm that the word 'insert' is in the correct language (NL for anything but locale of en-US).
I don't know the correct dutch and there seems to be difference with the `insert-label` translation.

Add translation for 'insert' in the sidebar

---

.changeset/smooth-maps-type.md
app/controllers/agendapoints/edit.js
app/controllers/meetings/edit/intro.js
app/controllers/meetings/edit/outro.js
app/controllers/regulatory-statements/edit.js

Since we often add extra attributes to the html loaded into the editor, comparing the html input and that in the editor always fails, so we think the document has been modified. Since we clear the undo state on save, we can instead use this to determine whether all changes have been saved. This misses changes that have been manually undone, such as adding, then deleting the same text but this feels like an acceptable trade for the simplicity of this solution.
https://binnenland.atlassian.net/browse/GN-4016
N/A
Open any agenda point or regulatory statement, optionally make some changes and undo them, then go back, you are no longer asked whether you want to leave with unsaved changes. If you have unsaved changes, it will ask to confirm.
As noted in the code, if we were to maintain the undo …

Use undo history to track 'isDirty' instead of comparing html strings

---

.changeset/dirty-goats-boil.md
.changeset/friendly-flies-arrive.md
.changeset/funny-chicken-arrive.md
.changeset/rich-mangos-bow.md
package-lock.json
package.json

This PR includes updates to the following packages:
- `@lblod/ember-rdfa-editor` to 9.0.0
- `@lblod/ember-rdfa-editor-lblod-plugins` to 16.0.0
- `@appuniversum/ember-appuniversum` to 2.15.0
- `ember-intl` to 6.1.0

Update editor packages

---

app/controllers/regulatory-statements/edit.js
app/styles/app.scss
app/templates/regulatory-statements/edit.hbs
package-lock.json
package.json

Mainly adding the snippet insert feature and the css import
just npm i and run, the plugins are connected with github link
Note: to connect to the futurenow RB backend when running locally, you'll need to change the endpoints in config/environment.js
I debated adding that here but I wanna avoid frantic debugging due to forgetting this was changed.

Enable rdfa mode for rbs and some tweaks

---

.changeset/gold-mirrors-bake.md
app/components/behandeling-van-agendapunt.js

This PR adds several null/undefined checks to the `behandeling-van-agendapunt` component in order to prevent `undefined` errors.
None
- Open up a meeting with agendapoints
- Remove an agendapoint
- The `container is undefined` error should no longer show up

Add null-checks to behandeling-van-agendapunt component (hotfix)

---

.changeset/gold-mirrors-bake.md
app/components/behandeling-van-agendapunt.js

This PR adds several null/undefined checks to the `behandeling-van-agendapunt` component in order to prevent `undefined` errors.
None
- Open up a meeting with agendapoints
- Remove an agendapoint
- The `container is undefined` error should no longer show up

Add null-checks to behandeling-van-agendapunt component

---

.changeset/nasty-bottles-pump.md
app/routes/application.js
app/utils/intl.js

This PR applies the same set of changes as https://github.com/lblod/ember-rdfa-editor/pull/1117, improving the detection of the user's browser language.
https://github.com/lblod/ember-rdfa-editor/pull/1117
Use [a locale switcher](https://addons.mozilla.org/en-US/firefox/addon/locale-switcher/) to try different combinations of locales and that it always translates the UI as expected. In that add-on you can select multiple locales by clicking the switch at the top:

Improve browser language detection and set nl-be fallback

---

.changeset/calm-llamas-protect.md
app/utils/intl.js
tests/unit/utils/intl-test.js

User preferred order of languages (e.g. from `navigator.languages`) was not taken into regard if _more_ preferred language did not match supported language code exactly, but there is an exactly matching less preferred language.
E.g.  user `navigator.languages` returns `['nl-NL', 'en-US']` but supported languages are `['nl-BE', 'en-US']`, then `decentLocaleMatch` function would return `['en-us', 'nl-be']`, as `en-US` was matched and added to the matched languages first because of how the code was structured.
* https://binnenland.atlassian.net/browse/GN-4772
Closes #642 
1. Checkout
2. `ember s --proxy https://dev.gelinkt-notuleren.lblod.info` 
You will need a Local Switcher extension installed. Set it up like so
Navigate to the application, it should be in Dutch. If you test without this …

GN-4772: Fix supported language detection

---

.changeset/fuzzy-hats-compete.md
.changeset/slimy-lobsters-admire.md
app/components/toolbar/list.hbs
app/components/zitting-text-document-container.js
app/controllers/agendapoints/edit.js
app/controllers/regulatory-statements/edit.js
package-lock.json
package.json

This PR includes two changes:
- Update of `@lblod/ember-rdfa-editor` to 9.7.0
- Support for hierarchical lists

Update `@lblod/ember-rdfa-editor` to 9.7.0 and enable support for hierarchical lists

---

.changeset/nine-wombats-stare.md
app/controllers/regulatory-statements/edit.js
app/styles/app.scss
package-lock.json
package.json

Add snippet placeholder nodespec and view so they are rendered correctly in RS editor. Required to use rdfa aware snippet insert component.
[binnenland.atlassian.net/browse/GN-4782](https://binnenland.atlassian.net/browse/GN-4782)
Uses: https://github.com/lblod/ember-rdfa-editor/pull/1188
And: https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/419
RB part: https://github.com/lblod/frontend-reglementaire-bijlage/pull/241
You'll need to get templates from the latest RB in order to have snippet placeholders, so need to change `regulatoryStatementEndpoint` and `regulatoryStatementFileEndpoint` to point to local and run the RB stack.
In RB, publish a template with a snippet placeholder, and verify that in GN you can select it and insert a relevant snippet.
I don't know if it was a …

Add snippet placeholder

---

.changeset/nine-wombats-stare.md
app/controllers/regulatory-statements/edit.js
app/styles/app.scss

These commits were in `futurenow` after #653 was merged, but are no longer there or in `master`.
As far as I can tell from examining the git history, these are the only commits that are missing.
#653 
N/A
Snippet placeholders work correctly in Regulatory statements.
It wasn't clear what rebase erased these commits, so the analysis was manual. I suggest `git push --force-with-lease` for anyone push-forcing to avoid this in the future.

Re-add snippet placeholder nodespecs

---

.changeset/yellow-mirrors-clap.md
app/components/document-attachments.hbs
app/components/signatures/notulen/behandelingen-list.hbs

The API of the AuToggleSwitch changed with the new version, so it broke
https://binnenland.atlassian.net/browse/GN-4834
Go to the document publication screen, you should see a label in all the switches

AuToggleSwitch must include the label as a block

---

.changeset/slimy-lobsters-accept.md
app/components/meeting-form.hbs

There was a wrong text block in the free text section
None, self discovered bug
Go to the meeting screen, the free text section should only include the correct text
It would be good if someone with familiarity with the meeting screen goes through and tries to see if anything else has changed, if we got this text maybe something else has also gone wrong.
I ran prettier and it didn't change back.

Wrong text block on Free text section

---

.changeset/long-ligers-argue.md
.woodpecker/.release.yml

The release woodpecker build is only pushing to the specific version tag, not to `:latest`, so `:latest` is actually pushed from the latest script. Woodpecker doesn't seem to run latest for the release commit, presumably either because it triggers the release pipeline, or because it's pushed at the same time, so there's only one 'push' event (not sure why it wouldn't pick the latest pushed commit though).
So until the first change to master after a release, `:latest` will always misreport as being the previous version.
N/A
N/A
Push a new tag and verify in docker hub that the shas for both that version and `latest` are the same.
I don't know for sure if this will work, their docs don't say how to specify multiple tags, but their code looks like just comma seperating works.

Correctly tag release builds as latest in docker hub

---

.changeset/giant-camels-glow.md
app/components/rdfa-editor-container.js

"Insert snippet" plugin depends on "activeNode". "activeNode" is derived by `editableNodePlugin`. `editableNodePlugin` is not enabled when `shouldEditRdfa` is `false`. Fixed that.
1. Checkout
2. `ember s --proxy https://gelinkt-notuleren.lblod.info` 
3. Mock login
https://github.com/lblod/frontend-gelinkt-notuleren/assets/769698/d8dbe1b1-72a3-4098-95e6-60e7c35502ab

GN-4825: Correctly shows "Insert snippet" button

---

.changeset/flat-apes-glow.md
app/templates/agendapoints/revisions.hbs

This PR ensures that the revisions of an agendapoint are correctly rendered on the 'revisions' page.
None
- Start-up the application
- Open an agendapoint and visit the revisions page
- Ensure that the revisions are correctly rendered

Fix rendering issue on agendapoint revisions page

---

.changeset/fair-carpets-argue.md
app/controllers/meetings/edit/intro.js
app/controllers/meetings/edit/outro.js

This PR ensures that the unsaved-changes dialog does not show up when selecting the `save and exit` button while editing the intro/outro of a meeting.
None
- Open a meeting and edit the intro or outro
- Select the `save and exit` button
- Ensure that the unsaved-changes dialog no longer shows up
This PR includes some changes in the logic of the intro and outro pages. It ensures that the `dirty` property is equal to `false` after having saved the document by clearing the `editor` property. The `editor` property then gets reinstated when a new editor instance is created just after saving.

Ensure unsaved-changes dialog does not show up when saving intro/outro of a meeting

---

.changeset/real-spiders-dance.md
app/styles/_shame.scss

Remove selection styling hacks that seem not relevant and broke links. This was introduced here: https://github.com/lblod/frontend-gelinkt-notuleren/pull/448 In order to tweak the styling of embedded regulatory statements in agenda points. Since it no longer seems possible to select these PM nodes, this styling never actually gets applied to these. The background color was however being applied to any selection, not just those in embedded regulatory statements, so was causing the input for the url of a link to have an invisible selection.
N/A
N/A
Insert a link, add a URL, then select part of the URL to see that it is highlighted. It's also worth checking that embedded regulatory statements behave as before.
N/A

Fix link URL input selection

---

.changeset/clever-pandas-suffer.md
app/components/rdfa-editor-container.js
package-lock.json
package.json

GN-4820: Bump editor and enable copy/pasting variable nodes correctly
* https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/435
* https://github.com/lblod/ember-rdfa-editor/pull/1195
1. Checkout
2. `npm i` 
See if copy/pasting variable works
https://github.com/lblod/frontend-gelinkt-notuleren/assets/769698/e965b1f5-7bca-4700-b084-9919dd92cd43

GN-4820: Bump editor and enable copy/pasting variable nodes correctly

---

.changeset/twelve-snakes-joke.md
app/services/document-service.js

With the change of the editor, we stopped using relative uris like `a` and started using `'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'` instead. We already make this fix on the plugins repo but failed to do here. We might need to do it somewhere else but don't know where so if someone knows another place is targeting relative uris let me know.
GN-4864
None
Create an agendapoint, write a description on it, then go to a meeting and try to add the agendapoint and copy its description. It should be copied correctly while previously it was not
As I said we could be missing the same fix on other places

Fixed document service not targeting the correct predicates

---

.changeset/shaggy-pugs-shave.md
app/components/document-creator/form.hbs
app/services/regulatory-attachments-fetcher.js

1. Allows to search for template in the dropdown when creating new regulatory statement
2. Sorts templates by title when fetching them from backend
https://binnenland.atlassian.net/browse/GN-4853
1. Checkout
3. `ember s --proxy https://dev.gelinkt-notuleren.lblod.info` 
4. Go to http://localhost:4200/inbox/regulatory-statements/new
https://github.com/lblod/frontend-gelinkt-notuleren/assets/769698/88fc987f-8e73-4c76-8230-82f853a2672f

GN-4853: Search and sort templates alphabetically

---

.changeset/kind-pots-end.md
app/components/meeting-form.js
package-lock.json
package.json

Includes some dependency updates but only those required to support the latest editor and plugins.
https://github.com/lblod/ember-rdfa-editor/pull/1204
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/448
N/A
Everything should work as before.
There is an issue with the agendapoints editor as [it imports `besluitNodes`](https://github.com/lblod/frontend-gelinkt-notuleren/blob/f48e125d54d60ebce90ca748eb8f73b1faea429b/app/controllers/agendapoints/edit.js#L67) from plugins which [has been removed](https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/449). I think it makes sense to make any changes for this in a separate PR.

Update to editor and plugins with updated dependencies

---

.changeset/gorgeous-dragons-bathe.md
app/components/participation-list.js

This PR fixes an issue in the `participation-list` component which displays the attendance of the different mandatees in a meeting. It corrects the approach in how absentees are fetched/retrieved.
[GN-4953](https://binnenland.atlassian.net/browse/GN-4953)
- Open the app
- Modify the attendance of a meeting (and add some absentees)
- The absentees should show up correctly
When relationships of a model are correctly loaded in the ember-data store, you can not retrieve these using javascript '.' getters. You can either use the `.get('...')` or `.belongsTo('...')` methods.

GN-4953: fix issue with meeting absentees not shown

---

.changeset/great-actors-peel.md
app/controllers/regulatory-statements/edit.js

This PR ensures that the `snippet` node-spec and nodeview are correctly added to the regulatory-statement editor configuration.
[GN-4958](https://binnenland.atlassian.net/browse/GN-4958)
- Open the application
- Create a regulatory statement based on a template which contains snippet placeholders
- You should be able to use the snippet placeholder to insert a snippet without issues

GN-4958: add `snippet` node and nodeview to regulatory-statement editor config

---

.changeset/tiny-islands-call.md
app/components/common/meeting-section.hbs
app/components/meeting-form.hbs

This PR re-adds the corrects ids to the different meeting section to ensure the sidebar links work as expected.
[GN-4954](https://binnenland.atlassian.net/browse/GN-4954)
- The different links included in the left sidebar should navigate you to the correct section

GN-4954: fix links in meeting sidebar

---

.changeset/spotty-paws-fail.md
app/components/agenda-manager/agenda-table/row.hbs
translations/en-us.yaml
translations/nl-BE.yaml

This PR adjusts the meeting design/UX in two ways:
- Removal of the edit button next to agenda items
- Make the title of agenda items clickable
[GN-4962](https://binnenland.atlassian.net/browse/GN-4962?atlOrigin=eyJpIjoiZDUwNjYwN2ZjY2M2NDUwODg4YTFiNjUxMGQ0MjE5NTciLCJwIjoiaiJ9)
- Notice that the edit button next to agenda items is gone
- If you click on the title of an agenda item, it should open the edit modal.

GN-4962: remove seperate edit button for agenda items

---

.changeset/nice-avocados-study.md
ember-cli-build.js

This PR excludes ember-leaflet assets from fingerprinting
[GN-4976](https://binnenland.atlassian.net/browse/GN-4976?atlOrigin=eyJpIjoiMTM5ZjEzZmUzZWFmNDZjYWI3ZTJmZWI5OWI1MmJhN2YiLCJwIjoiaiJ9)
Check-out https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/464 for more information.

GN-4976: exclude ember-leaflet assets from fingerprinting

---

.changeset/yellow-cougars-serve.md
package-lock.json
package.json

Bump plugins to 22.2.1 this will be keep on a experimental version until we merge and release the PR
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/466

bump plugins to 22.2.1

---

.changeset/wild-dogs-admire.md
app/components/editor-plugins/regulatory-statements/view.js
app/editor-plugins/regulatory-statements-plugin/index.js
package.json

…
When checking for RS updates we were making unnecesary changes and adding them to the history, which resulted in the editor thinking there were changes when there were not. This interfiered with the saving action.
I limited these changes, and I added a way of updating properties without adding them to the history
GN-4961
https://github.com/lblod/ember-rdfa-editor/pull/1214
Link the ember-rdfa-editor with the branch of the PR I linked
Go to the agendapoints, create a new agendapoint with a RS, save it and check that it doesn't say that it has unsaved changes anymore, modify the RS go back to the agendapoint and check that now you have a unsaved change to save
Maybe in the future we shouldn't require user action in order to update the RS

Don't make unnecessary history changes when updating RS inside agendapoints

---

.changeset/chilly-candles-mix.md
app/components/date-time-picker.js
translations/appuniversum/en-us.yaml

Since version 1.4.0, [duet-date-picker](https://github.com/duetds/date-picker) uses basic tables to represent the dropdown calendar. Since screen readers already know how to navigate html tables, the custom `keyboardInstruction` approach/message is now redundant. See https://github.com/duetds/date-picker/pull/87 for more info.
- Open the app
- Open a page where the date picker is used
- Notice that the calendar used by the date picker is implemented using a basic table

date-picker: drop `keyboardInstruction` setting

---

.changeset/dry-lions-smell.md
app/styles/project/_c-editor-preview.scss
app/styles/project/_c-template.scss
app/styles/project/_p-annotations.scss
app/styles/project/_u-print.scss

This PR adjusts the stylesheets of rdfa-annotations to also include full URIs.
Unsure if all these style rules are still needed.
Among others, this fixes the short description of decisions not being marked as public.
Not really proud of this PR :cry:
[GN-5000](https://binnenland.atlassian.net/browse/GN-5000?atlOrigin=eyJpIjoiNGZkZDA3YjMxYjFjNDdjYTk2NTgyYmI5MmFjZTllNWMiLCJwIjoiaiJ9)
- Open a meeting with agendapoints which contain decisions with descriptions
- Open the publish page with the 'notulen'/'document' tab
- Ensure that the 'short description' parts of the decisions are being marked as public.
As mentioned before, I am unsure if all these css rules are still necessary/used. We should probably prune them one day.
This solution is not ideal, but is what is …

GN-5000: adjust rdfa-annotation stylesheets to also include full URIs

---

.changeset/brave-nails-march.md
.changeset/four-impalas-fail.md
.changeset/gold-grapes-sniff.md
.changeset/thin-hotels-confess.md
app/components/meeting-form.js
app/components/participation-list/functionaris-selector.js
app/components/participation-list/mandataris-selector.js
app/components/participation-list/mandatarissen-table.hbs
app/utils/constants.js

This PR includes some improvements regarding the querying/displaying of mandatees in a meeting. Specifically, the following improvements are:
- Removal of a (duplicate) erroneous yield from the `mandatarissen-table` component
- `meeting-form.js`: improve filter of `possible-participants` query: the query now includes filtering on the `status`, `start` and `einde` fields, the post-query `isValidMandateeForMeeting` filter is no longer necessary
- `meeting-form.js`: adjust `possible-participants` query to include additional relationships to avoid spotty/patchy load of mandatee table
- `mandataris-selector.js`: improve filter of mandatee query:  the query now includes filtering on the `status`, `start` and `einde` fields, the post-query `isValidMandateeForMeeting` filter is no longer …

Meeting participants improvements

---

.changeset/chilled-bears-trade.md
.changeset/eleven-panthers-melt.md
.changeset/empty-rocks-check.md
app/components/zitting-text-document-container.js
app/controllers/agendapoints/edit.js
app/controllers/regulatory-statements/edit.js

This PR includes some changes in the rdfa-aware configuration (it enables the rdfa-aware setting where possible):
- agendapoint editor: enable rdfa-aware setting for `link`, `heading` and `doc` nodes
- RS editor: enable rdfa-aware setting for `link` node
- meeting intro/outro editor: enable rdfa-aware setting on all applicable nodes
None
- Open an agendapoint/regulatory-statement and notice that all applicable nodes are now rdfa-aware. Older documents should be correctly parsed.
- The intro/outro sections of a meeting should now also be rdfa-aware.
Unsure if I need to rebase this PR to an older version?

Enable rdfa-aware setting on remaining (non rdfa-aware) nodes

---

.changeset/popular-pugs-eat.md
app/controllers/inbox/meetings.js
app/controllers/inbox/meetings/new.js
app/routes/inbox/meetings/new.js
app/templates/inbox/meetings.hbs
app/templates/inbox/meetings/new.hbs
package-lock.json
package.json

This PR adds a meeting details modal to the inauguration meeting creation flow to allow users to specify the location and time of the meeting.
Differences compared to common meeting creation modal:
- Administrative unit is not editable
- Modal title is slightly different
Additionally, this PR also includes a modification in how the governing body (bestuurseenheid) is selected for the inauguration meeting:
- The `binding-einde` should be undefined or gte than the current date. (is this correct?)
[GN-4977](https://binnenland.atlassian.net/browse/GN-4977)
- Visit the meeting inbox
- Test if both the common meeting and inauguration meeting creation flows works as expected

GN-4977: add meeting details modal to inauguration meeting creation flow

---

.changeset/three-rice-brake.md
package-lock.json
package.json

This (draft) PR updates the editor-plugins to the dev commit found on https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/468. It implements collapsible snippet previews.
[GN-4937](https://binnenland.atlassian.net/browse/GN-4937?atlOrigin=eyJpIjoiOTg4ZDg4YmU5ZDViNDJhN2E4ZTM2NjBiZjg4MjNjMzUiLCJwIjoiaiJ9)
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/468
- Create a regulatory statement based on a template containing a snippet placeholder
- Open the 'Insert snippet' modal, and notice that you can preview each of the snippets listed

GN-4937: add support for snippet previews

---

.changeset/selfish-terms-nail.md
package-lock.json
package.json

This PR updates the `@lblod/ember-rdfa-editor-lblod-plugins` package to version 22.4.1

Update editor plugins to 22.4.1

---

.changeset/wicked-lamps-press.md
app/controllers/meetings/publish/notulen.js

This PR includes some modifications to the `meetings/publish/notulen` controller in how the deletion of signatures is handled.
Specifically, it ensures that the correct `versioned-notulen` resource is marked as deleted when all signatures are removed (the `full` kind, not the `public` kind).
[GN-5302](https://binnenland.atlassian.net/browse/GN-5032)
https://github.com/lblod/app-gelinkt-notuleren/pull/193
- Create a meeting
- Set the start and end dates
- Add an agendapoint
- Visit the publishing page
- Open up the `document`/`notulen` publish section
- Sign the `document`/`notulen`
- Remove the signature
- Change the end date (or other data) of the meeting
- Revisit the `document`/`notuleren` publish screen
- Click on the `sign` button
- Note that the preview is correctly updated with the …

GN-5032: ensure `versioned-notulen` resources related to signed resources are marked as `deleted` when all signatures are removed

---

config/environment.js
package-lock.json
package.json

Add support for loading environment variables from a `.env` file in `environment.js`. A `.env` file is only loaded when `environment` is 'development'.
The following variables are supported:
- `MOW_REGISTRY_SPARQL_ENDPOINT`
- `PUBLICATION_SPARQL_ENDPOINT`
- `ROADSIGN_IMAGE_BASE_URL`
- `FALLBACK_CODELIST_SPARQL_ENDPOINT`
- `REGULATORY_STATEMENT_ENDPOINT`
This ensures that a developer can easily override some variables inside a `.env` file (which is part of `.gitignore`), without needing to adjust the `environment.js` (and accidentally committing it).
None
- Try to add some of the above variables to your `.env` file and ensure the application uses them correctly.

dev-tooling: add support for `dotenv` when in environment.js file

---

.changeset/itchy-bobcats-think.md
app/components/download-document.hbs
app/components/download-document.js
app/controllers/agendapoints/edit.js
app/controllers/agendapoints/revisions.js
app/controllers/agendapoints/show.js
app/controllers/regulatory-statements/edit.js
app/controllers/regulatory-statements/revisions.js
app/controllers/regulatory-statements/show.js
app/templates/agendapoints/edit.hbs
app/templates/agendapoints/revisions.hbs
app/templates/agendapoints/show.hbs
app/templates/regulatory-statements/edit.hbs
app/templates/regulatory-statements/revisions.hbs
app/templates/regulatory-statements/show.hbs
app/utils/generate-export-from-editor-document.js
package-lock.json
package.json
translations/en-us.yaml
translations/nl-BE.yaml
tsconfig.json

Uses the util added to the editor repo to remove template comments when exporting (leaving the option to export as before).
Editor PR: https://github.com/lblod/ember-rdfa-editor/pull/1219
Plugins PR: https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/483
Jira ticket: [binnenland.atlassian.net/browse/GN-4999](https://binnenland.atlassian.net/browse/GN-4999)
N/A
Find an agendapoint or regulatory statement with template comments, save a new version.
*Saving again is important* as we need to save the template comments with the necessary data attribute to be removed.
Go to any screen with a 'file options' menu and check that the two export options work as expected (for publish means without comments). You might need to go in as a 'lezer' to get some of the screens.
I don't know if …

Add options to export HTML without template comments

---

.changeset/angry-lemons-hang.md
package-lock.json
package.json

This (draft) PR updates `@lblod/ember-rdfa-editor-lblod-plugins` to the dev build of https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/482. That PR adds support for the reworked snippet data-model and ordered snippets.
TODOS:
[GN-5005](https://binnenland.atlassian.net/browse/GN-5005)
https://github.com/lblod/frontend-reglementaire-bijlage/pull/279
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/482
https://github.com/lblod/app-reglementaire-bijlage/pull/84
Check-out https://github.com/lblod/frontend-reglementaire-bijlage/pull/279
Check-out https://github.com/lblod/frontend-reglementaire-bijlage/pull/279

GN-5005: reworked snippet data-model + support for ordered snippets

---

.changeset/loud-schools-hang.md
app/components/document-creator.js
package-lock.json
package.json

Made the document instantiator differentiate  if the template comes from RB and use the new instantiator for those
https://github.com/lblod/frontend-reglementaire-bijlage/pull/283
Create a template on RB using the new branch and check that it gets correctly instantiated on GN
None

Instantiate the templates coming from RB with the new library

---

.changeset/nervous-chefs-pretend.md
app/components/rdfa-editor-container.hbs
app/templates/agendapoints/edit.hbs
app/templates/regulatory-statements/edit.hbs

Always open insert menu and move insert snippet button to the bottom of the list
GN-5092
None
Go to agendapoints edit and RB edit and check that the insert menu is open by default and the insert snippet button is at the bottom
None

Always open insert menu and move insert snippet button to the bottom

---

app/config/constants.js
app/config/mandatee-table-config.js
app/utils/promises.js

This PR adds a mandatee-table config for the `IVGR5-LMB-1` section: splitsing van 'fracties' (fraction splitting).
It queries all 'kandidatenlijsten' (candidate lists) which result in two 'fracties'.
It then queries information about both fractions.
[GN-5089](https://binnenland.atlassian.net/browse/GN-5089?atlOrigin=eyJpIjoiYjcyNTQ0ZmFjNjNjNGM4OTkyM2ExZjZlZmNiNzg3NmMiLCJwIjoiaiJ9)
- Open an IV meeting and insert a 'IVGR5-LMB-1-splitsing-fracties' table into one of the agendapoints
- Press the sync button
- If using 'Aalst' as a municipality, you should see an example. Currently none of the two fractions will have any members shown. 
- Maybe we should show a message to the users if there are no candidate lists which splitted?
- Weird mix of english and dutch. Tried …

GN-5089: add config for fraction splitting

---

.changeset/two-bottles-raise.md
app/config/mandatee-table-config.js

This PR ensures that all GR LMB queries filter on the necessary 'bestuursfunctie-code':
- `IVGR2-LMB-1-geloofsbrieven`: filters on 'gemeenteraadslid'
- `IVGR3-LMB-1-eedafleggingen`: filters on 'gemeenteraadslid'
- `IVGR4-LMB-1-rangorde-gemeenteraadsleden`: filters on 'gemeenteraadslid'
- `IVGR5-LMB-1-splitsing-fracties`: filters on 'gemeenteraadslid'
- `IVGR5-LMB-2-grootte-fracties`: filters on 'gemeenteraadslid'
- `IVGR5-LMB-3-samenstelling-fracties`: filters on 'gemeenteraadslid'
- `IVGR7-LMB-1-kandidaat-schepenen`: filters on 'schepen'
- `IVGR7-LMB-2-ontvankelijkheid-schepenen`: filters on 'schepen'
- `IVGR8-LMB-1-verkozen-schepenen`: filters on 'schepen'
- `IVGR8-LMB-2-coalitie`: filters on 'schepen' and 'voorzitter bijzonder comite sociale dienst (BCSD)`
Most of the queries already …

LMB GR config: ensure bestuursfunctie is filtered on 'gemeenteraadslid' where necessary

---

.changeset/bright-dingos-watch.md
app/components/decision-copy-parts.gjs
app/components/meeting-form.hbs
app/components/meeting-form.js
app/controllers/meetings/download/copy.js
app/controllers/meetings/download/index.js
app/routes/meetings/download.js
app/routes/meetings/publish.js
app/styles/project/_c-meeting-chrome.scss
app/templates/meetings/download/copy.hbs
app/templates/meetings/download/index.hbs
app/templates/mock-login.hbs
translations/en-us.yaml
translations/nl-BE.yaml

Use query selectors to pull apart a decision document to pull out the individual parts, to allow for these to be pasted into an external editor. Should maintain all of the content of each section, without setting the URIs for the sections.
Builds on: https://github.com/lblod/frontend-gelinkt-notuleren/pull/728
Jira ticket: https://binnenland.atlassian.net/browse/GN-5067
N/A
You should be able to copy just the parts now. It should handle incomplete documents by simply not showing the parts it cannot find.
This is very hacky and it's not entirely clear what should be included in the copied contents.

Split out and copy parts of a decision

---

.changeset/fast-jokes-tie.md
app/components/decision-copy-parts.gjs
app/controllers/meetings/download/copy.js
app/styles/project/_c-inauguration-meeting-synchronization.scss
app/utils/copy-string-to-clipboard.js

There are 3 fixes here of increasing subtlety:
1. ~~Set the copy-all button on the copy screen to set the plaintext mime type as well as text/html.~~
2. Prevent articles from before the `data-say-structure-content` attribute was added to article nodes from crashing the component.
3. Extract the `outerHTML` of the section before extracting parts, as `append()`ing of content elements to a `div` element in the callback function removes them from the element, and so from the `outerHTML` if we generate it after doing this.
4. Working around Firefox stripping many RDFa attributes when using the clipboard API.
Fixes the result of https://github.com/lblod/frontend-gelinkt-notuleren/pull/731
Fixes: https://binnenland.atlassian.net/browse/GN-5127
N/A
For any meeting, go to the 'copy parts' screen …

Fixes to copy parts functionality

---

.changeset/clean-kings-turn.md
app/config/constants.js
app/routes/inbox/meetings/new-inauguration.js

This PR adjusts how we determine the correct 'BestuursorgaanClassificatiecode' to use when creating a new inauguration meeting.
Specifically, it adds an object which maps:
- 'Gemeente' to 'Gemeenteraad'
- 'OCMW' to 'Raad voor maatschappelijk welzijn'
- 'Provincie' to 'Provincieraad'
- 'District' to 'Districtsraad'
This way we can easily determine which 'BestuursorgaanClassificatiecode' to use based on the logged in 'Bestuurseenheid'.
None
- Log in as an OCMW/District/Gemeente
- Create a new inauguration meeting
- Notice that the correct bestuursorgaan-type is selected

IV: implement more extendable way to determine correct bestuursorgaan

---

.changeset/clean-kings-turn.md
.changeset/slow-seals-bathe.md
app/config/constants.js
app/config/mandatee-table-config.js
app/routes/inbox/meetings/new-inauguration.js

This PR introduces some bugfixes for the 'fractie-splitsing' LMB table query:
- Adjustment in how verkiezing and kieslijsten are determined (previous approach was erroneous)
- Fix an incorrect variable name
None
- Start the GN application
- Create/open an inauguration meeting
- Insert an LMB table with the `IVGR5-LMB-1-splitsing-fracties` tag
- When syncing, ensure the following
* The correct election resource is used to determine the kieslijsten + fracties
* It runs without error

fix(lmb-tables): adjust fractie-splitsing query

---

.changeset/clean-kings-turn.md
.changeset/fair-boxes-sleep.md
.changeset/slow-seals-bathe.md
app/components/inauguration-meeting/synchronization.js
app/config/constants.js
app/config/mandatee-table-config.js
app/routes/inbox/meetings/new-inauguration.js
app/services/editor/agendapoint.js
app/utils/editor-utils.js

This PR adds LMB-table configs for the 'Installatievergadering' of the 'Raad van maatschappelijk welzijn'.
Specifically, it adds configs for the following dynamic tables:
- 'Zetelverdeling van de BSCD (Bijzonder comite voor de sociale dienst)'
- 'Kandidaat-leden BSCD'
- 'Verkiezing leden BCSD' (this one contains the `mandaat:bekrachtigdAanstellingVan` annotations)
- 'Geloofsbrieven leden BSCD'
- 'Eedaflegging leden BCSD'
As you'll notice while testing this PR, some of these tables have empty cells which we can't derive/automatically fill-in based on LMB.
[GN-5088](https://binnenland.atlassian.net/browse/GN-5088)
None
- You'll need to test this PR logged in as an OCMW
- Create a new IV
- Add the necessary (configured with the new RMW tags) LMB tables in any AP (the second is the legally …

GN-5088: add LMB table configs for the RMW IV

---

.changeset/mighty-chairs-pull.md
app/components/zitting-text-document-container.js
app/controllers/regulatory-statements/edit.js
app/services/editor/agendapoint.js

This PR disables the `rdfaAware` setting on `heading` nodes for two main reasons:
- To ensure consistency with https://github.com/lblod/frontend-reglementaire-bijlage
- The `rdfaAware` setting never really worked very well in combination with `heading` nodes. Typically (IMO) it's not a good idea to mix markup/styled nodes (e.g. headings, paragraphs) with data nodes (block_rdfa, inline_rdfa...)
https://github.com/lblod/frontend-reglementaire-bijlage/pull/291
- Start the frontend
- Open any agendapoint/regulatory statement/intro,outro
- Notice that the heading nodes are no longer rdfa-aware: you can easily enter inside of them for example, no border around them...
- Check if the copy function still works as expected

Disable `rdfaAware` setting on `heading` nodes

---

.changeset/little-ravens-eat.md
.changeset/loud-tomatoes-add.md
app/components/inauguration-meeting/synchronization.js
app/config/constants.js
app/config/mandatee-table-config.js
app/controllers/regulatory-statements/edit.js
app/services/editor/agendapoint.js

This PR adjusts the IV LMB queries in the following way:
- The 'bestuursorgaan' who created the IV meeting is determined. This 'bestuursorgaan' will be either a:
* Districtsraad
* Gemeenteraad
* Bijzonder comité voor de sociale dienst (BCSD)
- Based on this 'bestuursorgaan', we can determine the 'bestuurseenheid'
- We check if the classificatie of the 'bestuurseenheid' is correct/relevant
- Based on the 'bestuurseenheid' and the correct 'bestuursperiode', we can determine which (other) 'bestuursorgaan' we need to select to query the mandatees/fractions from. Depending on the query, this will be either:
* Gemeenteraad
* College van burgemeester en schepenen
* Bijzonder comite voor de sociale dienst
Ensure you are running the latest version of the backend or are proxying to dev.
- Start the …

IV LMB queries: ensure the correct bestuursorgaan-in-tijd is selected

---

.changeset/silver-humans-smash.md
app/components/decision-copy-parts.gjs

Render the 'label' of decision parts to copy to the DOM temporarily, so we can use `innerText` and ignore any parts that are hidden from the user, such as the article number for single articles.
Jira bug: https://binnenland.atlassian.net/browse/GN-5161
N/A
Create a meeting with an agenda point, which has only one article. Then go to actions / download or copy / more copy options. The label for the article should now be `Enig artikel .` (without the number that used to be there).
It's not clear if the number should be there at all, but rather than change the HTML, just hack around it.

Add hack for handling single articles in copy-parts component

---

.changeset/tall-moles-flash.md
app/components/agenda-manager/agenda-table/row.hbs
app/styles/_shame.scss
app/styles/project/_c-editor-preview.scss
app/styles/project/_c-template.scss

Mostly styling changes to support changed prepublisher output. Also include the numbers when allowing to drag the agenda points into different positions. There were no designs, so hopefully this fits the desired outcome.
Expects a modified version of the prepublisher: https://github.com/lblod/notulen-prepublish-service/pull/116
Jira ticket: https://binnenland.atlassian.net/browse/GN-5043
Run the app-gn stack locally, with the PR version of the prepublisher
All steps of the meeting publish flow should consistently show the numbers next to the agenda point titles (not the decision titles).
N/A

Show agendapoint numbers in meeting publish flow

---

.changeset/six-crabs-think.md
app/components/zitting-text-document-container.js

This PR adds the `emberApplication` plugin to the `zitting-text-document-container` component editor config.
This ensure that nodes who might require it, can access the ember application instance (e.g. for intl).
https://github.com/lblod/frontend-reglementaire-bijlage/pull/294
None
- Ensure the intro/outro of the meeting has no prosemirror config issues (e.g. doesn't crash etc.)

`zitting-text-document-container`: add `emberApplication` plugin

---

.changeset/afraid-dodos-sparkle.md
app/templates/agendapoints/edit.hbs
config/environment.js

This PR hides the mandatee-table editor behind a feature-flag `mandatee-table-editor`.
By default, this flag is set to `false`. In development mode, it is set to `true`.
In a prod environment, you can control the feature-flag through the `EMBER_GN_FEATURE_MANDATEE_TABLE_EDITOR` environment variable.
None
None
- Open an agendapoint
- Notice that it is possible to insert a table/edit it
- Update the feature-flag to `false` in the `environment.js` file
- Restart the dev server
- Notice that the mandatee-table insert/edit features are now disabled

Hide mandatee-table editor behind feature-flag

---

.changeset/sweet-boxes-rush.md
app/api/installatievergadering.js

This PR ensures that the relevant decision templates get correctly instantiated upon an IV creation.
None
None
- Creation an IV
- Ensure that the (decision) URIs are correctly instantiated (no `--ref` etc.)

bugfix: ensure decision templates get correctly instantiated upon IV creation

---

.changeset/proud-wombats-give.md
app/api/installatievergadering.js

meeting start dates should default to the planned start rather than `now()`
[GN-5185](https://binnenland.atlassian.net/browse/GN-5185)

Set start date to planned start for new IVs

---

.changeset/real-buses-invite.md
app/controllers/inbox/meetings.js
app/templates/inbox/meetings.hbs

This PR ensures that the creation of inauguration meetings is only available to:
- Gemeentes
- Districten
- OCMWs
The logged-in administrative unit should be relevant for the next legislation (e.g. no old, no longer existing muncipalities)
None
None
- Log in as a (still-existing) gemeente, OCMW or district
- Ensure the option to create an IV is available
- Log in as a province or as a no-longer-existing administrative unit (e.g. a pre-fusion muncipality)
- Ensure the IV creation option is not available

Disable creation of IV if not applicable

---

.changeset/dirty-vans-boil.md
app/styles/_shame.scss
app/templates/meetings/download/index.hbs
translations/en-us.yaml
translations/nl-BE.yaml

Add agendapoint numbers to download table
Also changed the way the headers looked, as they had the style of a sortable header without being sortable
GN-5177
None
Go to the download table and see that the agendapoint number now appears on the left column 
None

Add agendapoint numbers to download table

---

.changeset/heavy-apricots-jump.md
.changeset/orange-kids-hug.md
app/services/editor/agendapoint.js
app/templates/agendapoints/edit.hbs
package-lock.json
package.json

Remove the '--ref-uuid4-' part used for templates and just use a uuidv4.
Most importantly, includes a version of the plugins that uses the uuid instantiator for snippet insertion, see [plugins PR](https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/498)
Includes: https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/498
Jira ticket: [binnenland.atlassian.net/browse/GN-5206](https://binnenland.atlassian.net/browse/GN-5206)
N/A
Insert a snippet which includes an article and also use the 'insert article' button and confirm that all articles have well-formed URIs. Easiest is to enable RDFa editing mode to verify this.
N/A

Correct URI generated when inserting decision articles

---

.changeset/early-pans-wink.md
app/controllers/regulatory-statements/edit.js
app/services/editor/agendapoint.js
package-lock.json
package.json

This PR includes two things:
- An update to the editor-plugins dev-commit created by https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/503
- Adjustments to the citation plugin configuration to ensure it follows the latest API and remains active in 'motivering' blocks.
[GN-5209](https://binnenland.atlassian.net/browse/GN-5209)
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/503
None
- Log in
- Open an agendapoint containing a decision
- Ensure that you can insert a citation in a 'motivering' block
- Open a regulatory statement
- The citation plugin should be active document-wide

GN-5209: fix citation plugin issues

---

.changeset/chatty-lemons-return.md
app/components/administrative-body-select.hbs
app/components/administrative-body-select.js
app/controllers/inbox/meetings/new.js
app/models/bestuursorgaan.js
app/templates/inbox/meetings/new.hbs

This PR adjusts the logic of the meeting creation dialog:
- Only allow the selection of 'bestuursorganen' which are active on the selected 'planned start' date
- When modifying the 'planned start' date, clear the 'bestuursorgaan' if necessary.
Additionally, this PR also modernizes the `administrative-body-select` component a bit (usage of `trackedFunction` and ensuring reactivity)
Should reduce issues like these: https://binnenland.atlassian.net/browse/GN-5216
- Log in as a municipality
- Open the meeting creation dialog
- Ensure that the list of 'bestuursorgaan' options changes based on the 'planned start` that is selected
- Ensure that the 'bestuursorgaan' field is cleared when you select a 'planned start' date on which the 'bestuursorgaan' is not active
- Meeting …

feat(meeting-creation): only allow bestuursorganen active at planned start date

---

.changeset/rich-pandas-protect.md
app/components/zitting-text-document-container.js
app/controllers/meetings/edit/custom-voting.js

The new ember application plugin was wrongly configured on Custom voting and zitting document text container
GN-5225
None
Don't really know other ways of testing this than trying to reproduce the bug in the linked jira issue and check that it doesn't happen anymore
None

Ember application plugin was wrongly configured on custom voting and zitting text container

---

.changeset/eight-forks-live.md
app/services/editor/agendapoint.js

While moving to the seperate `agendapoint` service, I forgot to configure the necessary RDFa plugins for the headless editor (this are plugins that are configured by default on a headful editor).
[GN-5239](https://binnenland.atlassian.net/browse/GN-5239)
- Login as a municipality/OCMW
- Open/create an IV
- Ensure at least one of the following mandatee tables is configured
* IVGR3-LMB-1-eedafleggingen
* IVGR7-LMB-2-ontvankelijkheid-schepenen
* IVRMW2-LBM-3-verkiezing-leden
- Sync the meeting
- Open the AP containing one of the 3 tables
- Ensure the RDFa is correct (the mandatees should be connected to the decision using the `mandaat:bekrachtigtAanstellingVan` predicate)

GN-5239: headless-editor - add necessary RDFa plugins

---

.changeset/nine-files-know.md
app/models/publishing-log.js

The config to make the link between publishing-log and zitting polymorphic was done incorrectly, so ember-data gave an error. I didn't see any issues from this yet other than the console error.
N/A
N/A
Publish an IV meeting and notice that there is no longer a console error.
N/A

Fix model config for publishing-log to correctly work with IVs

---

.changeset/hip-dogs-call.md
app/controllers/agendapoints/edit.js
app/services/editor/agendapoint.js

Fixes the bug with LMB syncing, as the table replacements were being calculated on the pre-autofilled state but run on the post-autofilled state.
Jira ticket: https://binnenland.atlassian.net/browse/GN-5256
Easiest to see when pointing to QA and either QA RB or prod RB.
This should take place in any template with an autofill variable in the document at some point before a mandatee table. An example of this is the IV for an OCMW, so logging in as one of these should work (see Jira comments for a list of exact municipalities).
1. Create an IV
2. Look at the preview of the APs to confirm that there is indeed an autofill variable, with a mandatee table somewhere later in the document. If you open an editor, do not save it.
3. Click the 'synchronize with LMB' button. This should work …

Do not autofill variables in a headless editor

---

.changeset/angry-guests-poke.md
app/api/installatievergadering.js

Ronse and Voeren where not getting agendapoints when creating a IV due to a configuration error
GN-5281
None
Login with Voeren or Ronse, both Geemente and OCMW, verify that you can successfully create IV and the agendapoints appear 
None

FIx bug when creating a IV with Ronse and Voeren

---

.changeset/honest-frogs-smile.md
app/config/mandatee-table-config.js

This PR includes adjustments to the SPARQL queries used to fill-in the mandatee tables.
Explicit `rdf:type` assertions are added to each type of resource consumed from LMB, in order to prevent us from querying tombstones.
[LMB-1105](https://binnenland.atlassian.net/browse/LMB-1105)
None
- Start the frontend
- Log in as an OCMW/Gemeente
- Open/create an IV
- Ensure all the mandatee tables are present in the IV (for ease-of-use, create an AP with all type of tables inside of it)
- Sync the meeting
- Check-out master
- Sync the meeting again
- Using the `versions` view of the AP, no difference should be noticed between the two versions
This PR provides a workaround so we don't need to specifically handle/cleanup tombstone resources ATM.

mandatee sparql-queries: don't query tombstones

---

.changeset/nice-pumas-fix.md
package-lock.json
package.json

Update `@lblod/ember-rdfa-editor` to version [10.9.0](https://github.com/lblod/ember-rdfa-editor/releases/tag/v10.9.0)

Update editor to version 10.9.0

---

.changeset/cuddly-bags-hang.md
.changeset/popular-ghosts-listen.md
app/api/installatievergadering.js
app/utils/map-with-default.js

This PR includes support for 'fusiegemeenten' to set up their inauguration meeting.
Specifically, the following changes are included:
- A slight rework of the `installatievergadering` api for readability. Includes a custom `Map` implementation with support for default values and batch-setting map entries
- The addition of the `fusietemplates` to the IV configuration
[GN-5309](https://binnenland.atlassian.net/browse/GN-5309)
Ensure that you're connected to QA/PROD RB
- Login as a 'fusiegemeente' gemeente/OCMW
- Ensure you can create both a 'gemeente' and 'OCMW' inauguration meeting
- You should still be able to create meetings in other municipalities
- Both 'Lokeren' and 'Antwerpen' should have no 'Politieraad' AP
I reworked the `installatievergadering` API to what I think …

GN-5309: add support for fusie IVs

---

.changeset/shy-dancers-joke.md
app/styles/_shame.scss
app/styles/project/_c-meeting-chrome.scss

This PR slightly modernizes the meeting page css by moving to a flex-based layout.
In terms of UX/UI the behaviour should have stayed more-or-less the same.
None
None
- Login as a municipality and open/create a meeting
- Both the behaviour of the sidebar and main content should have stayed the same:
* Both containers scroll independently
* Paddings have remained the same/similar
* The page is still more-or-less responsive: the sidebar disappears when reducing the width of the page + the main section takes full width

Modernize meeting page css

---

.changeset/two-walls-move.md
app/components/date-time-picker.hbs
app/components/date-time-picker.js

Use the au time picker instead of manual implementation of the same behaviour.
Solves GN-5280
None
Create a new meeting and check the time picker works as expected
The UI changes a little bit

update the date time picker to use the au time picker

---

.changeset/quiet-phones-grow.md
app/config/mandatee-table-config.js
app/config/mandatee-table-query-fragments.js

Uses the new hack of throwing the right election results into the db...
Jira ticket: [binnenland.atlassian.net/browse/GN-5315](https://binnenland.atlassian.net/browse/GN-5315)
Corrects: https://github.com/lblod/frontend-gelinkt-notuleren/pull/784
Needs the migrations from: https://github.com/lblod/app-gelinkt-notuleren/pull/221
Run pointing to a backend with the migrations.
Syncing an IV should produce the correct mandatee table sorting. It's especially useful to test for municipalities that have fractions with the same numbers of seats and those with lists made up of more than one fractie.
...

Sort mandatee tables by list results not candidate results

---

.changeset/early-rings-hope.md
app/config/constants.js
app/config/mandatee-table-config.js

This PR ensures that we include people with the 'Toegevoegde schepen' mandate in the 'Verkozen schepenen' table of IVGR8 (`IVGR8-LMB-1-verkozen-schepenen`)
[GN-5323](https://binnenland.atlassian.net/browse/GN-5323)
- Start the frontend
- Login as a municipality which contains a 'Toegevoegde schepen' in LMB
- Create/open an IV
- Sync the meeting
- In AP7: the 'toegevoegde schepen' should not be included in the tables (they are not known yet by that time)
- In AP8: the 'toegevoegde schepen' should be included in the table

GN-5323: include 'toegevoegde schepen' in IVGR8 mandatee table

---

.changeset/strong-rats-shave.md
app/components/document-creator.js

This PR ensures that we also apply the new `instantiateUuids` method when instantiating the built-in standard templates.
This PR should be backwards compatible and should thus also work with current versions of the backend.
[GN-5245](https://binnenland.atlassian.net/browse/GN-5245)
To be tested in conjunction with https://github.com/lblod/app-gelinkt-notuleren/pull/223
Check-out https://github.com/lblod/app-gelinkt-notuleren/pull/223
See https://github.com/lblod/app-gelinkt-notuleren/pull/223 for instructions on how to test

GN-5245: apply new template instantiate method on built-in standard templates

---

.changeset/dirty-buses-kick.md
app/controllers/regulatory-statements/edit.js
app/services/editor/agendapoint.js
package-lock.json
package.json

Just a matter of adding the new configuration.
Edit: now also includes location RDFa fix
A draft until the Plugins PR is in a release.
Plugins PR: https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/517
RB PR: https://github.com/lblod/frontend-reglementaire-bijlage/pull/306
Jira ticket: https://binnenland.atlassian.net/browse/GN-5022
N/A
Same as plugins PR, for agendapoints or RSs.
I wasn't sure if we should do this on RSs, but I made a guess.

Link locations to the surrounding document on insertion

---

.changeset/good-roses-run.md
app/components/behandeling-van-agendapunt.hbs
app/components/meeting-form.hbs
app/components/participation-list.hbs
app/components/participation-list/modal.hbs

Add loading indicator to the participation list of the meeting
GN-5012
None
Go to a meeting and notice that there's a loading indicator when you open the participation list of the meeting, you might need to activate throttling
None

add loading indicator to participation list

---

.changeset/quiet-news-compete.md
app/components/decision-copy.gjs
app/controllers/agendapoints/copy.js
app/controllers/meetings/download/copy.js
app/router.js
app/routes/agendapoints/copy.js
app/templates/agendapoints/copy.hbs
app/templates/agendapoints/edit.hbs
app/templates/meetings/download/copy.hbs
translations/en-us.yaml
translations/nl-BE.yaml

Add a way of copying the parts of an agendapoint direclty from the agendapoint and not from the meeting
GN-5321
None
Go to an agendapoint, in the file options you should have a copy decision parts button that should lead you to a new page where you can copy the decision parts
None

Add copy parts to the agendapoint

---

.changeset/breezy-eyes-refuse.md
app/controllers/meetings/publish/besluitenlijst.js
app/controllers/meetings/publish/notulen.js
app/services/publish.js
app/services/template-fetcher.js

When testing calls to prepublish service, I noticed that one of the calls was returning a 201 `created` status code, which was being interpreted as a failure. I changed this call and some others I found to use the `Response.ok` field instead of checking for 200. I also replaced the confusing `JSON.stringify(error)` call as an error always serialises as `{}`.
Found when creating https://github.com/lblod/notulen-prepublish-service/pull/124
This was found when working with an in-progress prepublisher which returned a 201 in place of a 200 for a job status. So, to test, you can run app-gn with a local version of the prepublisher. Modify the [`/prepublish/job-result/:jobUuid` route](https://github.com/lblod/notulen-prepublish-service/blob/b5cff84c0924b8cef5c0d5082591bebd13f60678/routes/preview. …

Fix publish service to handle non-200 success status codes

---

.changeset/curvy-lizards-suffer.md
app/services/template-fetcher.js

This PR solves an issue introduced in https://github.com/lblod/frontend-gelinkt-notuleren/pull/797
The `!response.ok` condition used in the `template-fetcher` should be `response.ok`.
None
None
Ensure you can correctly fetch + instantiate templates coming from RB.

Fix incorrect error handling in template-fetcher service

---

.changeset/green-tips-allow.md
package-lock.json
package.json

This PR includes a (dev-commit) editor update which fixes issues regarding the preservation of selections when having the `defaultAttributeValueGeneration` and/or `listTrackingPlugin` plugins enabled.
This fix also ensures that moving articles containg lists (e.g. mobility measures) can be done without issues.
https://github.com/lblod/ember-rdfa-editor/pull/1247
[GN-5228](https://binnenland.atlassian.net/browse/GN-5228?atlOrigin=eyJpIjoiNTA5NzAyNWIyZGEwNDlmMjg0NDQ0M2U3NTZmZjcyNjYiLCJwIjoiaiJ9)
Check-out https://github.com/lblod/ember-rdfa-editor/pull/1247

GN-5228: fix selection issues when moving articles

---

.changeset/funny-roses-give.md
.changeset/honest-mice-travel.md
app/services/editor/agendapoint.js
app/templates/agendapoints/edit.hbs
package-lock.json
package.json

This PR ensures that both the 'Insert traffic measure' and 'Insert article block' insert decision articles with correctly defined URIs (not placeholder URIs)
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/533
- Open/create an empty decision (with type 'reglement')
- Insert an article block and mobility measure
- Ensure both inserted articles have correctly defined URIs
There's a typo in the config of roadsign-regulation plugin, will fix this in a PR on the editor-plugins...

Fix issues related to decision article uri generation

---

.changeset/early-snails-cheat.md
app/components/agenda-manager/agenda-context.js
app/components/agenda-manager/agenda-table/body.hbs
app/components/agenda-manager/agenda-table/header.hbs
app/components/agenda-manager/agenda-table/row.hbs
app/styles/_shame.scss
app/styles/app.scss
app/styles/project/_c-meeting-chrome.scss
app/styles/project/_c-sortable.scss
config/environment.js
package-lock.json
package.json
tsconfig.json

This PR includes the following changes:
- Replace `ember-drag-drop` by `ember-sortable`
- Some slight adjustments to the styling of the meeting agenda table
- Set the deprecated `EXTEND_PROTOTYPES` flag to `false`
- Ensure the meeting agenda table works as you'd expect + the changes are correctly persisted
- There should be no issues caused by disabling the `EXTEND_PROTOTYPES` flag 
I made some slight css changes to the meeting agenda table, so it might behave slightly different. This is to make the behaviour consistent with the behaviour on RB, and to better align the styles with how `ember-sortable` behaves.

Remove `ember-drag-drop` dependency

---

.changeset/nasty-zebras-rhyme.md
package-lock.json
package.json

Updates `@lblod/ember-rdfa-editor-lblod-plugins` to version [26.5.0](https://github.com/lblod/ember-rdfa-editor-lblod-plugins/releases/tag/v26.5.0)

Update `@lblod/ember-rdfa-editor-lblod-plugins` to version 26.5.0

---

.changeset/cold-toes-happen.md
app/components/copy-parts/section.gjs
app/components/rb-copy-parts.gjs
app/controllers/regulatory-statements/copy.js
app/templates/regulatory-statements/edit.hbs
app/utils/copy-parts-update.js
translations/en-us.yaml
translations/nl-BE.yaml

Rb copy parts was working by accident on ember 4 and upgrading to ember 5 uncovered that some asumptions I made were plain wrong. This PR fixes all the faulty logic and also a missing translation I discovered on the demo
Didn't find it will link later
None
Check that rb still works as expected in ember 5
none

Use in element to fix rb copy parts

---

.changeset/friendly-dots-drop.md
app/styles/app.scss

This PR ensures that the editor styles are loaded before the app styles. This ensures that the app styles take priority over the styles of the appuniversum and editor packages.
[GN-5480](https://binnenland.atlassian.net/browse/GN-5480)
- Open a meeting page
- Ensure the styling of the meeting page is as expected
- Ensure the styles of an editor page have not changed
Unsure why we were loading the editor styles after the app styles, but this approach seems safer to me.

GN-5480: load editor styles before app styles

---

.changeset/empty-pens-drum.md
app/routes/application.js
config/environment.js

This PR introduces an application-wide `lang` query parameter which controls the display language of the application. By default, the language of the application is set to `nl-BE`, regardless of the user navigator languages/system locale.
[GN-5221](https://binnenland.atlassian.net/browse/GN-5221?atlOrigin=eyJpIjoiZjgyZWMwNWE4Y2ZkNGY1Zjk1MDkzMzlmZGMwM2VkNzYiLCJwIjoiaiJ9)
- Ensure the display language is dutch
- Add a `lang` query-param with e.g. `en-US`/`en-UK`
- Ensure the display language is now english
- The language should be persisted across reloads and route transitions
- Setting an unsupported language results in a dutch display language

GN-5221: introduce application-wide `lang` query-param

---

.changeset/wicked-vans-unite.md
app/components/document-creator/modal.gts
app/components/document-creator/template-picker.gts
app/config/environment.d.ts
app/controllers/inbox/agendapoints/new.js
app/services/document-service.ts
app/services/editor/agendapoint.ts
app/services/template-fetcher.ts

Removes the hacky approach to including standard templates by moving those templates to RB.
Fixes the problems with favourites and standard templates by making them no longer relevant.
For now the standard template service still exists as it is used by the standard template plugin.
Part of [binnenland.atlassian.net/browse/GN-5418](https://binnenland.atlassian.net/browse/GN-5418)
Built on https://github.com/lblod/frontend-gelinkt-notuleren/pull/838
Requires https://github.com/lblod/app-reglementaire-bijlage/pull/94
Also Requires (for favourites) https://github.com/lblod/app-gelinkt-notuleren/pull/228
For favourites to work, needs to be pointing to a GN [with the PR changes](https://github.com/lblod/app-gelinkt-notuleren/pull/228).
For standard templates to appear, needs to be pointing to …

Remove standard-template service from new AP controller

---

.changeset/long-toes-burn.md
config/environment.js

Those of us who speak dutch should always run GN in dutch to catch typos and mistakes as early as possible, as dutch is the "official" front-facing language. 
This pr does 2 things:
- exposes the language select to the process environment
- sets the default dev language back to dutch
Because we use the `dotenv` library, devs can now easily add `DEFAULT_LANGUAGE=en-us` to their `.env` file to set-and-forget the language to english.
I've reverted the default back to dutch for those rare occasions we get a visiting reviewer like niels or others. The baseline review experience should be as close to prod as possible, which currently chooses dutch regardless of browser locale. 
I hope that's a decent compromise @lagartoverde @piemonkey

feat: add ability to select default lang based on env var

---

.changeset/hungry-owls-rule.md
app/components/meeting-form.gts

Meeting navigation:
this PR removes the green checkmark icons from sections where no problems were found/no validation has been implemented.
- Meeting sections that do not have any validation issues, no longer have a green checkmark displayed next to them

feat(meeting-navigation): hide green checkmark icons

---

.changeset/short-maps-tease.md
app/models/behandeling-van-agendapunt.ts
app/models/zitting.ts
types/@ember-data/model.d.ts

This ensures that e.g. the meeting table-of-contents displays all agendapoints (up to a 100) of a meeting.
Also includes some type overrides for the `hasMany` function/decorator.
- Open a meeting with more than 20 ap's
- Ensure all ap's are displayed in the table-of-contents

fix: increase page-size-limit of agendapoints rel on zitting model

---

.changeset/yellow-crabs-wash.md
app/controllers/inbox/meetings.js
app/templates/inbox/meetings.hbs
config/environment.js

...
Jira ticket: https://binnenland.atlassian.net/browse/GN-5428
N/A
With flag = false, get a 'create meeting' button, with flag = true, get a dropdown.
N/A

Hide IV creation option behind a feature flag

---

.changeset/true-stars-talk.md
app/components/regulatory-statement-edit-citerra.gts
app/config/shacl-shapes.ts
app/styles/app.scss
package.json
pnpm-lock.yaml

Adds the 'for-now' configured SHACL validation plugin to RS for the Citerra PoC.
More tweaks and AP configuration will follow...
N/A
N/A
Best tested by pointing at GN dev and using the Citerra PoC templates to get documents to test.
N/A

Configure PoC SHACL validation for citerra RS

---

.changeset/thin-spiders-brake.md
app/styles/app.scss

While the padding on the table had been fixed, I realised the weird styling for roadsign templates in the traffic measure modal was caused by not actually using the stylesheet.
Related to https://binnenland.atlassian.net/browse/GN-5685
N/A
Open the 'insert traffic measure' modal and notice that long templates no longer overflow onto the next row.
N/A

Actually use roadsigns table styling
